-- =====================================================================
-- FORGE-X : Forensic Operations, Records, Governance & Evidence Exchange
-- File   : 09_seed_data.sql
-- Purpose: Realistic, fully self-consistent demo/test dataset covering
--          every table and the complete evidence lifecycle, including a
--          flagship case (CASE-2026-001) with rich narrative detail.
-- Depends: 01_create_database.sql, 02_tables.sql, 03_constraints.sql,
--          04_indexes.sql must already have run.
--
-- GENERATION METHOD
--   This file was generated by a small deterministic Python script
--   (scripts/generate_seed_data.py) rather than typed by hand, so that
--   ~450+ rows across 21 interdependent tables stay perfectly
--   referentially consistent (every FK value is guaranteed to exist)
--   while still reading as realistic, narratively coherent case data —
--   not Lorem-Ipsum filler. No randomness is used: every value is
--   picked deterministically from realistic-but-fictional pools, so
--   the output is 100% reproducible.
--
-- FICTIONAL DATA NOTICE
--   All names, badge numbers, national ID numbers, IP addresses, device
--   serials/IMEIs, and case content below are entirely fictional and
--   were constructed for this demo. No real person's data is used.
-- =====================================================================

USE forge_x;

-- Defensive: ensures THIS session sends/receives utf8mb4 regardless of
-- how the client was invoked (protects against a classic gotcha: running
-- `mysql -u root < this_file.sql` without --default-character-set=utf8mb4
-- silently corrupts any non-ASCII literal in this file via latin1
-- misinterpretation at write time -- discovered and fixed during Step 6
-- backend integration testing).
SET NAMES utf8mb4;

SET SESSION sql_mode = 'STRICT_ALL_TABLES,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
SET time_zone = '+00:00';

START TRANSACTION;
-- =====================================================================
-- 1. roles
-- =====================================================================
INSERT INTO roles (role_name, role_description) VALUES
    ('ADMIN', 'Full system access; manages users, roles, and departments'),
    ('LEAD_INVESTIGATOR', 'Owns and directs cases end-to-end: cases, investigators, persons, devices, evidence, reports'),
    ('INVESTIGATOR', 'Works assigned cases: assigned cases (read), evidence, and case timeline'),
    ('FORENSIC_ANALYST', 'Performs technical examination of evidence: evidence, examinations, reports'),
    ('EVIDENCE_CUSTODIAN', 'Manages physical custody hand-offs: evidence custody transfers'),
    ('VIEWER', 'Read-only access across the system; no write permissions anywhere');

-- =====================================================================
-- 2. departments
-- =====================================================================
INSERT INTO departments (department_name, department_code) VALUES
    ('Cyber Crime Cell', 'CCC'),
    ('Digital Forensics Lab', 'DFL'),
    ('IT Security Division', 'ITSD'),
    ('Legal & Compliance Unit', 'LCU');

-- =====================================================================
-- 3. locations
-- =====================================================================
INSERT INTO locations (location_name, location_type, address_line, city, state, postal_code) VALUES
    ('Central Evidence Locker', 'evidence_locker', 'MG Road Annex, Building C', 'Pune', 'Maharashtra', '411001'),
    ('Regional Forensics Lab', 'lab', 'Hinjewadi IT Park, Phase 2', 'Pune', 'Maharashtra', '411057'),
    ('State Cyber Cell Headquarters', 'field_site', 'Bandra-Kurla Complex', 'Mumbai', 'Maharashtra', '400051'),
    ('Metro Evidence Storage Facility', 'storage_facility', 'Andheri East Industrial Estate', 'Mumbai', 'Maharashtra', '400093'),
    ('Southern Digital Forensics Lab', 'lab', 'Electronic City Phase 1', 'Bengaluru', 'Karnataka', '560100'),
    ('District Court Complex', 'court', 'Shivajinagar Court Road', 'Pune', 'Maharashtra', '411005'),
    ('Eastern Zone Evidence Locker', 'evidence_locker', 'Hitech City Road', 'Hyderabad', 'Telangana', '500081'),
    ('National Cyber Forensics Lab', 'lab', 'Dwarka Sector 10', 'Delhi', 'Delhi', '110075');

-- =====================================================================
-- 4. case_types
-- =====================================================================
INSERT INTO case_types (type_name, type_description) VALUES
    ('Cybercrime', 'Offenses committed using computer networks or digital devices as the primary vector'),
    ('Data Breach', 'Unauthorized access to or exfiltration of confidential/sensitive data'),
    ('Fraud', 'Financial or corporate fraud with a digital evidence component'),
    ('Malware Incident', 'Ransomware, worms, trojans, or other malicious-software incidents'),
    ('Intellectual Property Theft', 'Theft or unauthorized use of proprietary digital assets');

-- =====================================================================
-- 5. device_types
-- =====================================================================
INSERT INTO device_types (type_name, type_description) VALUES
    ('Smartphone', 'Mobile handset (Android/iOS)'),
    ('Laptop', 'Portable personal computer'),
    ('Desktop Computer', 'Fixed workstation/personal computer'),
    ('External Hard Disk Drive', 'Portable external storage drive'),
    ('USB Flash Drive', 'Removable USB flash/thumb drive'),
    ('Server', 'Rack or standalone server hardware'),
    ('Network Router', 'Network routing/switching hardware'),
    ('Tablet', 'Tablet-class mobile device');

-- =====================================================================
-- 6. evidence_types
-- =====================================================================
INSERT INTO evidence_types (type_name, type_description) VALUES
    ('Disk Image', 'Bit-for-bit forensic image of a storage medium'),
    ('Memory Dump', 'Captured volatile RAM snapshot'),
    ('Log File', 'System, application, or network log extract'),
    ('Photograph', 'Photographic documentation of physical evidence or a scene'),
    ('Document Scan', 'Scanned physical or digitally-native document'),
    ('Network Capture', 'Captured network traffic (PCAP)'),
    ('Email Archive', 'Exported email mailbox or message archive'),
    ('Mobile Device Backup', 'Full or partial backup extracted from a mobile device');

-- =====================================================================
-- 7. forensic_tools
-- =====================================================================
INSERT INTO forensic_tools (tool_name, vendor, version, license_type) VALUES
    ('Autopsy', 'Basis Technology', '4.21', 'open_source'),
    ('EnCase Forensic', 'OpenText', '24.1', 'commercial'),
    ('FTK (Forensic Toolkit)', 'Exterro', '7.6', 'commercial'),
    ('Wireshark', 'Wireshark Foundation', '4.2', 'open_source'),
    ('Volatility 3', 'Volatility Foundation', '2.5', 'open_source'),
    ('Cellebrite UFED', 'Cellebrite', '7.60', 'commercial'),
    ('X-Ways Forensics', 'X-Ways Software Technology', '20.9', 'commercial'),
    ('Magnet AXIOM', 'Magnet Forensics', '7.5', 'commercial');

-- =====================================================================
-- 8. users
-- =====================================================================
INSERT INTO users (badge_number, username, email, password_hash, full_name, role_id, department_id, phone_number) VALUES
    ('FX-B-1001', 'asharma', 'a.sharma@forgex.gov.in', '$2b$12$ForgeXDemoOnlyNotARealBcryptHashPlaceholder1234567890', 'Ananya Sharma', 2, 1, '+91-98220-11001'),
    ('FX-B-1002', 'rverma', 'r.verma@forgex.gov.in', '$2b$12$ForgeXDemoOnlyNotARealBcryptHashPlaceholder1234567890', 'Rohan Verma', 4, 2, '+91-98220-11002'),
    ('FX-B-1003', 'pnair', 'p.nair@forgex.gov.in', '$2b$12$ForgeXDemoOnlyNotARealBcryptHashPlaceholder1234567890', 'Priya Nair', 4, 2, '+91-98220-11003'),
    ('FX-B-1004', 'kiyer', 'k.iyer@forgex.gov.in', '$2b$12$ForgeXDemoOnlyNotARealBcryptHashPlaceholder1234567890', 'Karthik Iyer', 2, 1, '+91-98220-11004'),
    ('FX-B-1005', 'mjoshi', 'm.joshi@forgex.gov.in', '$2b$12$ForgeXDemoOnlyNotARealBcryptHashPlaceholder1234567890', 'Meera Joshi', 2, 3, '+91-98220-11005'),
    ('FX-B-1006', 'areddy', 'a.reddy@forgex.gov.in', '$2b$12$ForgeXDemoOnlyNotARealBcryptHashPlaceholder1234567890', 'Arjun Reddy', 3, 2, '+91-98220-11006'),
    ('FX-B-1007', 'dmenon', 'd.menon@forgex.gov.in', '$2b$12$ForgeXDemoOnlyNotARealBcryptHashPlaceholder1234567890', 'Divya Menon', 6, 4, '+91-98220-11007'),
    ('FX-B-1008', 'srao', 's.rao@forgex.gov.in', '$2b$12$ForgeXDemoOnlyNotARealBcryptHashPlaceholder1234567890', 'Siddharth Rao', 1, 1, '+91-98220-11008'),
    ('FX-B-1009', 'nkulkarni', 'n.kulkarni@forgex.gov.in', '$2b$12$ForgeXDemoOnlyNotARealBcryptHashPlaceholder1234567890', 'Neha Kulkarni', 5, 3, '+91-98220-11009'),
    ('FX-B-1010', 'vsingh', 'v.singh@forgex.gov.in', '$2b$12$ForgeXDemoOnlyNotARealBcryptHashPlaceholder1234567890', 'Vikram Singh', 3, 1, '+91-98220-11010');

-- =====================================================================
-- 9. persons
-- =====================================================================
INSERT INTO persons (first_name, last_name, date_of_birth, national_id_number, gender, phone_number, email) VALUES
    ('Ramesh', 'Chandran', '1982-03-14', 'NID-FX-770001', 'male', '+91-90110-22001', 'ramesh.chandran@examplemail.test'),
    ('Sunita', 'Deshmukh', '1979-11-02', 'NID-FX-770002', 'female', '+91-90110-22002', 'sunita.deshmukh@examplemail.test'),
    ('Alok', 'Bhattacharya', '1990-06-21', NULL, 'male', '+91-90110-22003', 'alok.bhattacharya@examplemail.test'),
    ('Farhan', 'Sheikh', '1985-01-09', 'NID-FX-770004', 'male', '+91-90110-22004', 'farhan.sheikh@examplemail.test'),
    ('Kavita', 'Menon', '1993-09-30', NULL, 'female', '+91-90110-22005', 'kavita.menon@examplemail.test'),
    ('Nikhil', 'Agarwal', '1988-04-17', 'NID-FX-770006', 'male', '+91-90110-22006', 'nikhil.agarwal@examplemail.test'),
    ('Rajesh', 'Pillai', '1976-12-25', 'NID-FX-770007', 'male', '+91-90110-22007', 'rajesh.pillai@examplemail.test'),
    ('Sanjana', 'Rao', '1991-07-08', NULL, 'female', '+91-90110-22008', 'sanjana.rao@examplemail.test'),
    ('Imran', 'Qureshi', '1987-02-19', 'NID-FX-770009', 'male', '+91-90110-22009', 'imran.qureshi@examplemail.test'),
    ('Deepa', 'Krishnan', '1994-05-27', 'NID-FX-770010', 'female', '+91-90110-22010', 'deepa.krishnan@examplemail.test');

-- =====================================================================
-- 10. cases
-- =====================================================================
INSERT INTO cases (case_number, case_title, case_type_id, status, priority, jurisdiction_location_id, description, opened_at, closed_at, created_by) VALUES
    ('CASE-2026-001', 'Corporate Cyber Fraud Investigation', 3, 'under_investigation', 'high', 3, 'Suspected internal financial fraud at a mid-sized manufacturing firm, involving falsified vendor invoices and unauthorized fund transfers routed through compromised finance-department workstations.', '2026-01-05 09:00:00', NULL, 1),
    ('CASE-2026-002', 'Ransomware Attack on Regional Logistics Network', 4, 'open', 'critical', 6, 'A logistics company''s order-management server and several workstations were encrypted overnight; a ransom note references a double-extortion threat to leak exfiltrated shipment data.', '2026-01-11 09:00:00', NULL, 5),
    ('CASE-2026-003', 'Data Exfiltration by Former IT Administrator', 2, 'closed', 'medium', 3, 'A departing IT administrator is alleged to have copied customer databases to a personal external drive in the two weeks prior to resignation.', '2025-11-26 09:00:00', '2026-01-02 09:00:00', 4),
    ('CASE-2026-004', 'Phishing Campaign Targeting Municipal Finance Office', 1, 'pending_review', 'medium', 6, 'A spear-phishing email impersonating a vendor led to a municipal finance clerk disclosing portal credentials, resulting in a fraudulent payment redirection attempt.', '2026-01-15 09:00:00', NULL, 10),
    ('CASE-2026-005', 'Cryptocurrency Wallet Theft Investigation', 3, 'archived', 'low', 3, 'A private individual''s cryptocurrency wallet was drained following a compromised seed-phrase backup stored in an unencrypted note on a personal laptop.', '2025-10-27 09:00:00', '2025-12-16 09:00:00', 1);

-- =====================================================================
-- 11. case_investigators
-- =====================================================================
INSERT INTO case_investigators (case_id, user_id, role_in_case, assigned_at) VALUES
    (1, 1, 'lead_investigator', '2026-01-05 09:00:00'),
    (1, 2, 'forensic_analyst', '2026-01-05 11:00:00'),
    (1, 4, 'supervisor', '2026-01-05 12:00:00'),
    (2, 5, 'lead_investigator', '2026-01-11 09:00:00'),
    (2, 6, 'forensic_analyst', '2026-01-11 10:00:00'),
    (3, 9, 'forensic_analyst', '2025-11-26 09:00:00'),
    (3, 4, 'supervisor', '2025-11-26 10:00:00'),
    (4, 10, 'lead_investigator', '2026-01-15 09:00:00'),
    (4, 3, 'forensic_analyst', '2026-01-15 11:00:00'),
    (5, 1, 'lead_investigator', '2025-10-27 09:00:00'),
    (5, 7, 'consultant', '2025-10-28 09:00:00');

-- =====================================================================
-- 12. case_persons
-- =====================================================================
INSERT INTO case_persons (case_id, person_id, person_role, notes, linked_at) VALUES
    (1, 1, 'suspect', 'Finance department manager with approval access to the vendor-payment workflow.', '2026-01-05 13:00:00'),
    (1, 2, 'person_of_interest', 'External vendor contact flagged in multiple falsified invoices.', '2026-01-05 14:00:00'),
    (1, 3, 'witness', 'Junior accountant who first noticed the invoice discrepancies.', '2026-01-05 15:00:00'),
    (2, 6, 'suspect', 'Attribution under investigation via ransom-note communication channel.', '2026-01-11 11:00:00'),
    (2, 7, 'victim', 'IT operations head for the affected logistics firm.', '2026-01-11 12:00:00'),
    (2, 4, 'witness', 'Third-party contractor who observed unusual server activity before the incident.', '2026-01-11 13:00:00'),
    (3, 8, 'suspect', 'Departing IT administrator; resignation effective two weeks after alleged exfiltration.', '2025-11-26 11:00:00'),
    (3, 3, 'witness', 'Colleague who noticed unusual after-hours database export activity.', '2025-11-27 09:00:00'),
    (3, 5, 'victim', 'Data Protection Officer representing the affected customer database owner.', '2025-11-28 09:00:00'),
    (4, 9, 'suspect', 'Sender of the spear-phishing email under investigation.', '2026-01-15 10:00:00'),
    (4, 5, 'witness', 'Municipal finance clerk who received and acted on the phishing email.', '2026-01-15 11:00:00'),
    (5, 10, 'victim', 'Wallet owner whose cryptocurrency holdings were drained.', '2025-10-27 10:00:00'),
    (5, 2, 'person_of_interest', 'Contact linked to the destination wallet address in early tracing.', '2025-10-28 09:00:00');

-- =====================================================================
-- 13. devices
-- =====================================================================
INSERT INTO devices (case_id, device_type_id, owner_person_id, serial_number, make, model, imei_number, storage_capacity_gb, seized_at, seized_location_id, current_location_id, device_status) VALUES
    (1, 1, 1, 'SNCF10021A', 'Samsung', 'Galaxy S23', '356123451234561', NULL, '2026-01-05 10:00:00', 3, 2, 'under_examination'),
    (1, 2, 1, 'SNCF10022B', 'Dell', 'Latitude 5540', NULL, 512.0, '2026-01-05 10:00:00', 3, 2, 'under_examination'),
    (1, 3, 2, 'SNCF10023C', 'HP', 'EliteDesk 800 G9', NULL, 1024.0, '2026-01-05 11:00:00', 3, 2, 'in_lab'),
    (1, 4, 3, 'SNCF10024D', 'Seagate', 'Backup Plus 2TB', NULL, 2048.0, '2026-01-05 11:00:00', 3, 2, 'in_lab'),
    (2, 6, NULL, 'SNRL20051X', 'Dell', 'PowerEdge R440', NULL, 4096.0, '2026-01-11 10:00:00', 6, 5, 'under_examination'),
    (2, 2, 7, 'SNRL20052Y', 'Lenovo', 'ThinkPad T14', NULL, 512.0, '2026-01-11 11:00:00', 6, 5, 'in_lab'),
    (2, 7, NULL, 'SNRL20053Z', 'Cisco', 'ISR 4331', NULL, NULL, '2026-01-11 12:00:00', 6, 5, 'seized'),
    (3, 3, 8, 'SNDE30081M', 'Dell', 'OptiPlex 7010', NULL, 1024.0, '2025-11-26 10:00:00', 3, 1, 'returned'),
    (3, 5, 8, 'SNDE30082N', 'SanDisk', 'Ultra Dual Drive 128GB', NULL, 0.128, '2025-11-26 10:00:00', 3, 1, 'returned'),
    (3, 4, NULL, 'SNDE30083P', 'WD', 'Elements 1TB', NULL, 1024.0, '2025-11-26 11:00:00', 3, 1, 'returned'),
    (4, 1, 9, 'SNPH40111Q', 'Apple', 'iPhone 13', '356123457654321', NULL, '2026-01-15 10:00:00', 6, 2, 'under_examination'),
    (4, 2, 9, 'SNPH40112R', 'HP', 'ProBook 440 G9', NULL, 512.0, '2026-01-15 10:00:00', 6, 2, 'in_lab'),
    (4, 8, NULL, 'SNPH40113S', 'Samsung', 'Galaxy Tab A8', '356123459998887', NULL, '2026-01-15 11:00:00', 6, 2, 'seized'),
    (5, 1, 10, 'SNCT50141T', 'Apple', 'iPhone 12', '356123450001112', NULL, '2025-10-27 10:00:00', 3, 1, 'returned'),
    (5, 2, 10, 'SNCT50142U', 'Asus', 'ZenBook 14', NULL, 512.0, '2025-10-27 10:00:00', 3, 1, 'returned');

-- =====================================================================
-- 14. evidence
-- =====================================================================
INSERT INTO evidence (evidence_number, case_id, device_id, evidence_type_id, description, file_path, file_size_bytes, acquisition_method, collected_by, collected_at, storage_location_id, integrity_status) VALUES
    ('EVD-2026-001', 1, 1, 1, 'Full physical disk image of the seized Samsung Galaxy S23 (SNCF10021A) belonging to suspect Ramesh Chandran.', '/evidence/case-001/EVD-2026-001.dd', 128849018880, 'physical_extraction', 2, '2026-01-05 11:00:00', 2, 'intact'),
    ('EVD-2026-002', 1, 2, 1, 'Forensic disk image of the Dell Latitude 5540 laptop assigned to the finance department manager.', '/evidence/case-001/EVD-2026-002.E01', 549755813888, 'physical_extraction', 2, '2026-01-05 11:30:00', 2, 'intact'),
    ('EVD-2026-003', 1, 2, 2, 'Live RAM capture taken from the Dell Latitude 5540 laptop prior to shutdown.', '/evidence/case-001/EVD-2026-003.mem', 17179869184, 'logical_extraction', 2, '2026-01-05 11:45:00', 2, 'intact'),
    ('EVD-2026-004', 1, 3, 3, 'Extracted Windows Event Logs from the EliteDesk 800 workstation covering the fraud window.', '/evidence/case-001/EVD-2026-004-eventlogs.zip', 47185920, 'logical_extraction', 1, '2026-01-05 12:00:00', 2, 'intact'),
    ('EVD-2026-005', 1, NULL, 4, 'Photographic documentation of the seizure scene at the finance department office.', '/evidence/case-001/EVD-2026-005-photos.zip', 62914560, 'manual_documentation', 1, '2026-01-05 10:00:00', 2, 'intact'),
    ('EVD-2026-006', 1, 4, 5, 'Scanned set of falsified vendor invoices recovered from the external hard disk drive.', '/evidence/case-001/EVD-2026-006-invoices.pdf', 18874368, 'manual_documentation', 4, '2026-01-05 13:00:00', 2, 'intact'),
    ('EVD-2026-007', 1, 3, 7, 'Exported Outlook mailbox archive from the EliteDesk workstation covering vendor correspondence.', '/evidence/case-001/EVD-2026-007-mailbox.pst', 2147483648, 'logical_extraction', 2, '2026-01-05 12:30:00', 2, 'intact'),
    ('EVD-2026-008', 1, NULL, 6, 'Network traffic capture from the finance department VLAN during the suspected transfer window.', '/evidence/case-001/EVD-2026-008-capture.pcap', 314572800, 'network_capture', 1, '2026-01-05 14:00:00', 2, 'intact'),
    ('EVD-2026-009', 2, 5, 1, 'Forensic image of the PowerEdge R440 order-management server disk array.', '/evidence/case-002/EVD-2026-009.E01', 2199023255552, 'physical_extraction', 6, '2026-01-11 11:00:00', 8, 'intact'),
    ('EVD-2026-010', 2, 5, 2, 'RAM capture of the compromised order-management server prior to isolation.', '/evidence/case-002/EVD-2026-010.mem', 34359738368, 'logical_extraction', 6, '2026-01-11 11:15:00', 8, 'under_verification'),
    ('EVD-2026-011', 2, 7, 3, 'Router configuration and connection logs extracted from the Cisco ISR 4331.', '/evidence/case-002/EVD-2026-011-router.log', 8388608, 'logical_extraction', 5, '2026-01-11 12:00:00', 8, 'intact'),
    ('EVD-2026-012', 2, NULL, 6, 'Full packet capture of the logistics network during the ransomware encryption event.', '/evidence/case-002/EVD-2026-012.pcap', 943718400, 'network_capture', 5, '2026-01-11 13:00:00', 8, 'intact'),
    ('EVD-2026-013', 2, 6, 1, 'Disk image of the first workstation observed encrypted, belonging to the IT operations head.', '/evidence/case-002/EVD-2026-013.E01', 549755813888, 'physical_extraction', 6, '2026-01-11 11:30:00', 8, 'intact'),
    ('EVD-2026-014', 2, NULL, 5, 'Scanned copy of the printed ransom note left on affected workstation desktops.', '/evidence/case-002/EVD-2026-014-ransomnote.pdf', 2097152, 'manual_documentation', 5, '2026-01-11 14:00:00', 8, 'intact'),
    ('EVD-2026-015', 3, 8, 1, 'Disk image of the departing IT administrator''s OptiPlex 7010 workstation.', '/evidence/case-003/EVD-2026-015.E01', 1099511627776, 'physical_extraction', 9, '2025-11-26 10:00:00', 2, 'intact'),
    ('EVD-2026-016', 3, 8, 3, 'Database access and export logs recovered from the OptiPlex workstation.', '/evidence/case-003/EVD-2026-016-dblogs.zip', 15728640, 'logical_extraction', 9, '2025-11-26 10:30:00', 2, 'intact'),
    ('EVD-2026-017', 3, 9, 1, 'Disk image of the SanDisk USB flash drive seized from the administrator''s desk.', '/evidence/case-003/EVD-2026-017.dd', 128974848, 'physical_extraction', 9, '2025-11-26 11:00:00', 2, 'compromised'),
    ('EVD-2026-018', 3, NULL, 5, 'Scanned HR resignation and exit-interview paperwork referenced in the case timeline.', '/evidence/case-003/EVD-2026-018-hrdocs.pdf', 5242880, 'manual_documentation', 4, '2025-11-26 12:00:00', 2, 'intact'),
    ('EVD-2026-019', 3, 10, 7, 'Cloud mailbox export recovered from a backup stored on the WD Elements external drive.', '/evidence/case-003/EVD-2026-019-mailbox.pst', 1073741824, 'cloud_extraction', 9, '2025-11-26 11:30:00', 2, 'intact'),
    ('EVD-2026-020', 3, NULL, 4, 'Photographs of the administrator''s workstation and desk area at the time of seizure.', '/evidence/case-003/EVD-2026-020-photos.zip', 41943040, 'manual_documentation', 4, '2025-11-26 09:45:00', 2, 'intact'),
    ('EVD-2026-021', 4, 11, 8, 'Full mobile backup extracted from the suspect''s iPhone 13 used to send the phishing email.', '/evidence/case-004/EVD-2026-021-backup.tar', 8589934592, 'logical_extraction', 3, '2026-01-15 10:00:00', 2, 'intact'),
    ('EVD-2026-022', 4, 12, 7, 'Mailbox export from the ProBook 440 laptop containing phishing campaign correspondence.', '/evidence/case-004/EVD-2026-022-mailbox.pst', 268435456, 'logical_extraction', 3, '2026-01-15 10:30:00', 2, 'intact'),
    ('EVD-2026-023', 4, 13, 3, 'Browser and application logs extracted from the Galaxy Tab A8.', '/evidence/case-004/EVD-2026-023-browserlogs.zip', 6291456, 'logical_extraction', 10, '2026-01-15 11:00:00', 2, 'intact'),
    ('EVD-2026-024', 4, NULL, 5, 'Printed copies of the phishing email as received by the municipal finance clerk.', '/evidence/case-004/EVD-2026-024-phishingemail.pdf', 1048576, 'manual_documentation', 10, '2026-01-15 11:30:00', 2, 'intact'),
    ('EVD-2026-025', 4, NULL, 6, 'Network capture of the municipal finance office covering the credential-disclosure incident.', '/evidence/case-004/EVD-2026-025.pcap', 157286400, 'network_capture', 3, '2026-01-15 12:00:00', 2, 'intact'),
    ('EVD-2026-026', 5, 14, 8, 'Mobile backup extracted from the victim''s iPhone 12 used to access the cryptocurrency wallet app.', '/evidence/case-005/EVD-2026-026-backup.tar', 4294967296, 'logical_extraction', 1, '2025-10-27 10:00:00', 5, 'intact'),
    ('EVD-2026-027', 5, 15, 1, 'Disk image of the ZenBook 14 laptop where the seed-phrase note was stored.', '/evidence/case-005/EVD-2026-027.E01', 549755813888, 'physical_extraction', 1, '2025-10-27 10:30:00', 5, 'intact'),
    ('EVD-2026-028', 5, 15, 2, 'RAM capture of the ZenBook 14 laptop at the time of seizure.', '/evidence/case-005/EVD-2026-028.mem', 17179869184, 'logical_extraction', 7, '2025-10-27 10:45:00', 5, 'intact'),
    ('EVD-2026-029', 5, NULL, 5, 'Scanned printout of the blockchain transaction history for the drained wallet.', '/evidence/case-005/EVD-2026-029-txnhistory.pdf', 3145728, 'manual_documentation', 1, '2025-10-27 11:00:00', 5, 'intact'),
    ('EVD-2026-030', 5, NULL, 4, 'Photographs documenting the laptop and surrounding desk area at the time of seizure.', '/evidence/case-005/EVD-2026-030-photos.zip', 20971520, 'manual_documentation', 7, '2025-10-27 11:15:00', 5, 'intact');

-- =====================================================================
-- 15. evidence_hashes
-- Uses MySQL's native SHA2() to derive a realistic, valid 64-char hex
-- hash per evidence item directly from its evidence_number + acquisition
-- timestamp, so every row is guaranteed unique and passes the
-- chk_evidence_hashes_length CHECK constraint (>= 32 chars) trivially.
-- =====================================================================
INSERT INTO evidence_hashes (evidence_id, hash_algorithm, hash_value, computed_by, computed_at, is_original)
SELECT
    e.evidence_id,
    'SHA256',
    SHA2(CONCAT(e.evidence_number, '|original|', e.collected_at), 256),
    e.collected_by,
    e.collected_at + INTERVAL 15 MINUTE,
    1
FROM evidence e;
-- Re-verification hashes for the flagship case's evidence (demonstrates
-- is_original = 0 and repeated integrity checks over time).
INSERT INTO evidence_hashes (evidence_id, hash_algorithm, hash_value, computed_by, computed_at, is_original)
SELECT
    e.evidence_id,
    'SHA256',
    SHA2(CONCAT(e.evidence_number, '|reverify-30d|', e.collected_at), 256),
    e.collected_by,
    e.collected_at + INTERVAL 30 DAY,
    0
FROM evidence e
WHERE e.case_id = 1;
-- =====================================================================
-- 16. chain_of_custody
-- =====================================================================
INSERT INTO chain_of_custody (evidence_id, transferred_from, transferred_to, custody_action, location_id, custody_timestamp, remarks) VALUES
    (1, NULL, 2, 'collected', 3, '2026-01-05 11:00:00', 'Evidence collected at seizure site and logged into initial custody.'),
    (1, 2, 1, 'received', 2, '2026-01-05 13:00:00', 'Received at Regional Forensics Lab and logged in for forensic processing.'),
    (1, 1, 4, 'analyzed', 2, '2026-01-06 11:00:00', 'Checked out of controlled storage for active forensic analysis.'),
    (1, 4, 1, 'stored', 2, '2026-01-06 14:00:00', 'Analysis session complete; evidence re-secured in controlled storage.'),
    (2, NULL, 2, 'collected', 3, '2026-01-05 11:30:00', 'Evidence collected at seizure site and logged into initial custody.'),
    (2, 2, 1, 'received', 2, '2026-01-05 13:30:00', 'Received at Regional Forensics Lab and logged in for forensic processing.'),
    (2, 1, 4, 'analyzed', 2, '2026-01-06 11:30:00', 'Checked out of controlled storage for active forensic analysis.'),
    (2, 4, 1, 'stored', 2, '2026-01-06 14:30:00', 'Analysis session complete; evidence re-secured in controlled storage.'),
    (3, NULL, 2, 'collected', 3, '2026-01-05 11:45:00', 'Evidence collected at seizure site and logged into initial custody.'),
    (3, 2, 1, 'received', 2, '2026-01-05 13:45:00', 'Received at Regional Forensics Lab and logged in for forensic processing.'),
    (3, 1, 4, 'analyzed', 2, '2026-01-06 11:45:00', 'Checked out of controlled storage for active forensic analysis.'),
    (3, 4, 1, 'stored', 2, '2026-01-06 14:45:00', 'Analysis session complete; evidence re-secured in controlled storage.'),
    (4, NULL, 1, 'collected', 3, '2026-01-05 12:00:00', 'Evidence collected at seizure site and logged into initial custody.'),
    (4, 1, 2, 'received', 2, '2026-01-05 14:00:00', 'Received at Regional Forensics Lab and logged in for forensic processing.'),
    (4, 2, 4, 'analyzed', 2, '2026-01-06 12:00:00', 'Checked out of controlled storage for active forensic analysis.'),
    (4, 4, 2, 'stored', 2, '2026-01-06 15:00:00', 'Analysis session complete; evidence re-secured in controlled storage.'),
    (5, NULL, 1, 'collected', 3, '2026-01-05 10:00:00', 'Evidence collected at seizure site and logged into initial custody.'),
    (5, 1, 2, 'received', 2, '2026-01-05 12:00:00', 'Received at Regional Forensics Lab and logged in for forensic processing.'),
    (5, 2, 4, 'analyzed', 2, '2026-01-06 10:00:00', 'Checked out of controlled storage for active forensic analysis.'),
    (5, 4, 2, 'stored', 2, '2026-01-06 13:00:00', 'Analysis session complete; evidence re-secured in controlled storage.'),
    (6, NULL, 4, 'collected', 3, '2026-01-05 13:00:00', 'Evidence collected at seizure site and logged into initial custody.'),
    (6, 4, 1, 'received', 2, '2026-01-05 15:00:00', 'Received at Regional Forensics Lab and logged in for forensic processing.'),
    (6, 1, 2, 'analyzed', 2, '2026-01-06 13:00:00', 'Checked out of controlled storage for active forensic analysis.'),
    (6, 2, 1, 'stored', 2, '2026-01-06 16:00:00', 'Analysis session complete; evidence re-secured in controlled storage.'),
    (7, NULL, 2, 'collected', 3, '2026-01-05 12:30:00', 'Evidence collected at seizure site and logged into initial custody.'),
    (7, 2, 1, 'received', 2, '2026-01-05 14:30:00', 'Received at Regional Forensics Lab and logged in for forensic processing.'),
    (7, 1, 4, 'analyzed', 2, '2026-01-06 12:30:00', 'Checked out of controlled storage for active forensic analysis.'),
    (7, 4, 1, 'stored', 2, '2026-01-06 15:30:00', 'Analysis session complete; evidence re-secured in controlled storage.'),
    (8, NULL, 1, 'collected', 3, '2026-01-05 14:00:00', 'Evidence collected at seizure site and logged into initial custody.'),
    (8, 1, 2, 'received', 2, '2026-01-05 16:00:00', 'Received at Regional Forensics Lab and logged in for forensic processing.'),
    (8, 2, 4, 'analyzed', 2, '2026-01-06 14:00:00', 'Checked out of controlled storage for active forensic analysis.'),
    (8, 4, 2, 'stored', 2, '2026-01-06 17:00:00', 'Analysis session complete; evidence re-secured in controlled storage.'),
    (9, NULL, 6, 'collected', 6, '2026-01-11 11:00:00', 'Evidence collected at seizure site and logged into initial custody.'),
    (9, 6, 5, 'received', 8, '2026-01-11 13:00:00', 'Received at National Cyber Forensics Lab and logged in for forensic processing.'),
    (10, NULL, 6, 'collected', 6, '2026-01-11 11:15:00', 'Evidence collected at seizure site and logged into initial custody.'),
    (10, 6, 5, 'received', 8, '2026-01-11 13:15:00', 'Received at National Cyber Forensics Lab and logged in for forensic processing.'),
    (11, NULL, 5, 'collected', 6, '2026-01-11 12:00:00', 'Evidence collected at seizure site and logged into initial custody.'),
    (11, 5, 6, 'received', 8, '2026-01-11 14:00:00', 'Received at National Cyber Forensics Lab and logged in for forensic processing.'),
    (12, NULL, 5, 'collected', 6, '2026-01-11 13:00:00', 'Evidence collected at seizure site and logged into initial custody.'),
    (12, 5, 6, 'received', 8, '2026-01-11 15:00:00', 'Received at National Cyber Forensics Lab and logged in for forensic processing.'),
    (13, NULL, 6, 'collected', 6, '2026-01-11 11:30:00', 'Evidence collected at seizure site and logged into initial custody.'),
    (13, 6, 5, 'received', 8, '2026-01-11 13:30:00', 'Received at National Cyber Forensics Lab and logged in for forensic processing.'),
    (14, NULL, 5, 'collected', 6, '2026-01-11 14:00:00', 'Evidence collected at seizure site and logged into initial custody.'),
    (14, 5, 6, 'received', 8, '2026-01-11 16:00:00', 'Received at National Cyber Forensics Lab and logged in for forensic processing.'),
    (15, NULL, 9, 'collected', 3, '2025-11-26 10:00:00', 'Evidence collected at seizure site and logged into initial custody.'),
    (15, 9, 4, 'received', 2, '2025-11-26 12:00:00', 'Received at Regional Forensics Lab and logged in for forensic processing.'),
    (16, NULL, 9, 'collected', 3, '2025-11-26 10:30:00', 'Evidence collected at seizure site and logged into initial custody.'),
    (16, 9, 4, 'received', 2, '2025-11-26 12:30:00', 'Received at Regional Forensics Lab and logged in for forensic processing.'),
    (17, NULL, 9, 'collected', 3, '2025-11-26 11:00:00', 'Evidence collected at seizure site and logged into initial custody.'),
    (17, 9, 4, 'received', 2, '2025-11-26 13:00:00', 'Received at Regional Forensics Lab and logged in for forensic processing.'),
    (18, NULL, 4, 'collected', 3, '2025-11-26 12:00:00', 'Evidence collected at seizure site and logged into initial custody.'),
    (18, 4, 9, 'received', 2, '2025-11-26 14:00:00', 'Received at Regional Forensics Lab and logged in for forensic processing.'),
    (19, NULL, 9, 'collected', 3, '2025-11-26 11:30:00', 'Evidence collected at seizure site and logged into initial custody.'),
    (19, 9, 4, 'received', 2, '2025-11-26 13:30:00', 'Received at Regional Forensics Lab and logged in for forensic processing.'),
    (20, NULL, 4, 'collected', 3, '2025-11-26 09:45:00', 'Evidence collected at seizure site and logged into initial custody.'),
    (20, 4, 9, 'received', 2, '2025-11-26 11:45:00', 'Received at Regional Forensics Lab and logged in for forensic processing.'),
    (21, NULL, 3, 'collected', 6, '2026-01-15 10:00:00', 'Evidence collected at seizure site and logged into initial custody.'),
    (21, 3, 10, 'received', 2, '2026-01-15 12:00:00', 'Received at Regional Forensics Lab and logged in for forensic processing.'),
    (22, NULL, 3, 'collected', 6, '2026-01-15 10:30:00', 'Evidence collected at seizure site and logged into initial custody.'),
    (22, 3, 10, 'received', 2, '2026-01-15 12:30:00', 'Received at Regional Forensics Lab and logged in for forensic processing.'),
    (23, NULL, 10, 'collected', 6, '2026-01-15 11:00:00', 'Evidence collected at seizure site and logged into initial custody.'),
    (23, 10, 3, 'received', 2, '2026-01-15 13:00:00', 'Received at Regional Forensics Lab and logged in for forensic processing.'),
    (24, NULL, 10, 'collected', 6, '2026-01-15 11:30:00', 'Evidence collected at seizure site and logged into initial custody.'),
    (24, 10, 3, 'received', 2, '2026-01-15 13:30:00', 'Received at Regional Forensics Lab and logged in for forensic processing.'),
    (25, NULL, 3, 'collected', 6, '2026-01-15 12:00:00', 'Evidence collected at seizure site and logged into initial custody.'),
    (25, 3, 10, 'received', 2, '2026-01-15 14:00:00', 'Received at Regional Forensics Lab and logged in for forensic processing.'),
    (26, NULL, 1, 'collected', 3, '2025-10-27 10:00:00', 'Evidence collected at seizure site and logged into initial custody.'),
    (26, 1, 7, 'received', 5, '2025-10-27 12:00:00', 'Received at Southern Digital Forensics Lab and logged in for forensic processing.'),
    (27, NULL, 1, 'collected', 3, '2025-10-27 10:30:00', 'Evidence collected at seizure site and logged into initial custody.'),
    (27, 1, 7, 'received', 5, '2025-10-27 12:30:00', 'Received at Southern Digital Forensics Lab and logged in for forensic processing.'),
    (28, NULL, 7, 'collected', 3, '2025-10-27 10:45:00', 'Evidence collected at seizure site and logged into initial custody.'),
    (28, 7, 1, 'received', 5, '2025-10-27 12:45:00', 'Received at Southern Digital Forensics Lab and logged in for forensic processing.'),
    (29, NULL, 1, 'collected', 3, '2025-10-27 11:00:00', 'Evidence collected at seizure site and logged into initial custody.'),
    (29, 1, 7, 'received', 5, '2025-10-27 13:00:00', 'Received at Southern Digital Forensics Lab and logged in for forensic processing.'),
    (30, NULL, 7, 'collected', 3, '2025-10-27 11:15:00', 'Evidence collected at seizure site and logged into initial custody.'),
    (30, 7, 1, 'received', 5, '2025-10-27 13:15:00', 'Received at Southern Digital Forensics Lab and logged in for forensic processing.');

-- =====================================================================
-- 17. evidence_examinations
-- =====================================================================
INSERT INTO evidence_examinations (evidence_id, tool_id, examiner_id, examination_type, started_at, completed_at, findings_summary, examination_status) VALUES
    (1, 6, 2, 'data_recovery', '2026-01-06 09:00:00', '2026-01-06 15:00:00', 'Recovered deleted messaging app data referencing an external vendor account under investigation.', 'completed'),
    (2, 1, 2, 'static_analysis', '2026-01-06 11:00:00', '2026-01-06 18:00:00', 'File-system timeline shows batch creation of invoice PDFs outside normal business hours.', 'completed'),
    (3, 5, 4, 'dynamic_analysis', '2026-01-06 10:00:00', NULL, 'Memory analysis in progress; reviewing process list for unauthorized remote-access tooling.', 'in_progress'),
    (7, 8, 2, 'timeline_analysis', '2026-01-07 09:00:00', '2026-01-07 14:00:00', 'Email correspondence timeline corroborates invoice submission dates from three flagged vendor accounts.', 'peer_reviewed'),
    (9, 2, 6, 'static_analysis', '2026-01-12 09:00:00', '2026-01-12 17:00:00', 'Identified ransomware binary and lateral-movement artifacts consistent with a known ransomware family.', 'completed'),
    (10, 5, 6, 'dynamic_analysis', '2026-01-12 10:00:00', '2026-01-12 19:00:00', 'Volatile memory confirms an active encryption process and an outbound C2 connection at time of capture.', 'completed'),
    (11, 4, 5, 'network_analysis', '2026-01-12 11:00:00', '2026-01-12 16:00:00', 'Router logs show an unusual outbound connection shortly before the encryption event began.', 'completed'),
    (12, 4, 5, 'network_analysis', '2026-01-12 12:00:00', NULL, 'Deep packet inspection of the capture ongoing to map the full extent of data exfiltration.', 'in_progress'),
    (13, 6, 6, 'file_carving', '2026-01-13 09:00:00', '2026-01-13 15:00:00', 'Carved partially-encrypted files to recover fragments of the pre-encryption directory structure.', 'completed'),
    (15, 3, 9, 'static_analysis', '2025-11-27 09:00:00', '2025-11-27 16:00:00', 'File access timestamps show bulk database export activity in the two weeks before resignation.', 'completed'),
    (17, 3, 9, 'data_recovery', '2025-11-27 17:00:00', '2025-11-28 09:00:00', 'Recovered previously deleted export archive from unallocated space on the USB drive.', 'peer_reviewed'),
    (19, 7, 9, 'static_analysis', '2025-11-28 09:00:00', '2025-11-29 09:00:00', 'Mailbox review identifies correspondence with a personal email address matching the export window.', 'completed'),
    (16, 1, 4, 'timeline_analysis', '2025-11-29 09:00:00', '2025-11-30 09:00:00', 'Cross-referenced database logs against badge-access records to confirm after-hours presence.', 'completed'),
    (21, 6, 3, 'data_recovery', '2026-01-16 09:00:00', '2026-01-16 14:00:00', 'Extracted sent-message history confirming the phishing email was composed and sent from this device.', 'completed'),
    (22, 8, 3, 'static_analysis', '2026-01-16 10:00:00', '2026-01-16 15:00:00', 'Mailbox headers confirm domain spoofing consistent with the vendor-impersonation phishing template.', 'completed'),
    (23, 7, 10, 'static_analysis', '2026-01-16 11:00:00', NULL, 'Reviewing cached browser sessions for evidence of the fraudulent payment portal.', 'in_progress'),
    (25, 4, 3, 'network_analysis', '2026-01-17 09:00:00', '2026-01-17 13:00:00', 'Traffic capture confirms the finance office workstation submitted credentials to the spoofed portal.', 'completed'),
    (26, 6, 1, 'data_recovery', '2025-10-28 09:00:00', '2025-10-28 14:00:00', 'Recovered wallet application session data confirming the device used to authorize the transfer.', 'completed'),
    (27, 1, 7, 'static_analysis', '2025-10-28 10:00:00', '2025-10-28 18:00:00', 'Located an unencrypted notes file containing what appears to be the wallet seed phrase.', 'completed'),
    (28, 5, 7, 'dynamic_analysis', '2025-10-28 11:00:00', '2025-10-28 15:00:00', 'Memory artifacts consistent with clipboard-hijacking malware active at the time of the transfer.', 'peer_reviewed');

-- =====================================================================
-- 18. forensic_reports
-- =====================================================================
INSERT INTO forensic_reports (report_number, case_id, title, prepared_by, reviewed_by, report_status, created_at, finalized_at) VALUES
    ('RPT-2026-001', 1, 'Preliminary Forensic Findings - Corporate Cyber Fraud', 2, 4, 'finalized', '2026-01-07 09:00:00', '2026-01-08 09:00:00'),
    ('RPT-2026-002', 1, 'Device Examination Report - Seized Laptop and Desktop', 2, 1, 'approved', '2026-01-08 09:00:00', NULL),
    ('RPT-2026-003', 1, 'Vendor Correspondence and Email Timeline Analysis', 2, NULL, 'draft', '2026-01-09 09:00:00', NULL),
    ('RPT-2026-004', 2, 'Ransomware Incident Technical Report', 6, 5, 'under_review', '2026-01-13 09:00:00', NULL),
    ('RPT-2026-005', 2, 'Network Traffic and Exfiltration Assessment', 5, NULL, 'submitted', '2026-01-14 09:00:00', NULL),
    ('RPT-2026-006', 3, 'Data Exfiltration Findings Report', 9, 4, 'finalized', '2025-11-29 09:00:00', '2025-12-01 09:00:00'),
    ('RPT-2026-007', 3, 'USB Media Recovery and Timeline Report', 9, 4, 'approved', '2025-11-30 09:00:00', NULL),
    ('RPT-2026-008', 4, 'Phishing Campaign Technical Findings', 3, 10, 'under_review', '2026-01-17 09:00:00', NULL),
    ('RPT-2026-009', 4, 'Mobile Device Extraction Summary', 3, NULL, 'submitted', '2026-01-18 09:00:00', NULL),
    ('RPT-2026-010', 5, 'Cryptocurrency Wallet Theft Final Report', 1, 7, 'finalized', '2025-12-11 09:00:00', '2025-12-16 09:00:00');

-- =====================================================================
-- 19. report_versions
-- =====================================================================
INSERT INTO report_versions (report_id, version_number, file_path, content_hash, change_summary, created_by, created_at) VALUES
    (1, 1, '/reports/RPT-2026-001-v1.pdf', NULL, 'Initial draft circulated for supervisor review.', 2, '2026-01-07 09:00:00'),
    (1, 2, '/reports/RPT-2026-001-v2.pdf', NULL, 'Revised per supervisor feedback; added vendor cross-reference appendix.', 2, '2026-01-08 09:00:00'),
    (2, 1, '/reports/RPT-2026-002-v1.pdf', NULL, 'Initial device examination summary.', 2, '2026-01-08 09:00:00'),
    (2, 2, '/reports/RPT-2026-002-v2.pdf', NULL, 'Added memory-dump findings after Lead Investigator review.', 2, '2026-01-08 15:00:00'),
    (3, 1, '/reports/RPT-2026-003-v1.pdf', NULL, 'First draft of the email timeline analysis.', 2, '2026-01-09 09:00:00'),
    (4, 1, '/reports/RPT-2026-004-v1.pdf', NULL, 'Initial technical report on the ransomware incident.', 6, '2026-01-13 09:00:00'),
    (5, 1, '/reports/RPT-2026-005-v1.pdf', NULL, 'Initial network/exfiltration assessment.', 5, '2026-01-14 09:00:00'),
    (5, 2, '/reports/RPT-2026-005-v2.pdf', NULL, 'Updated with deep-packet-inspection findings.', 5, '2026-01-14 19:00:00'),
    (6, 1, '/reports/RPT-2026-006-v1.pdf', NULL, 'Final data exfiltration findings report.', 9, '2025-11-29 09:00:00'),
    (7, 1, '/reports/RPT-2026-007-v1.pdf', NULL, 'USB media recovery and timeline summary.', 9, '2025-11-30 09:00:00'),
    (8, 1, '/reports/RPT-2026-008-v1.pdf', NULL, 'Initial phishing campaign technical findings.', 3, '2026-01-17 09:00:00'),
    (9, 1, '/reports/RPT-2026-009-v1.pdf', NULL, 'Initial mobile extraction summary.', 3, '2026-01-18 09:00:00'),
    (9, 2, '/reports/RPT-2026-009-v2.pdf', NULL, 'Added browser cache analysis section.', 3, '2026-01-18 17:00:00'),
    (10, 1, '/reports/RPT-2026-010-v1.pdf', NULL, 'Final cryptocurrency wallet theft report.', 1, '2025-12-11 09:00:00');

-- =====================================================================
-- 20. case_timeline
-- =====================================================================
INSERT INTO case_timeline (case_id, event_type, event_description, related_table, related_record_id, event_timestamp, recorded_by) VALUES
    (1, 'case_opened', 'Case CASE-2026-001 opened following an internal fraud referral from the finance department.', 'cases', 1, '2026-01-05 09:00:00', 1),
    (1, 'evidence_collected', 'Seizure team collected 4 devices from the finance department office.', 'devices', 1, '2026-01-05 10:00:00', 1),
    (1, 'evidence_collected', 'Disk images and memory capture acquired from suspect''s laptop and phone.', 'evidence', 2, '2026-01-05 11:30:00', 2),
    (1, 'evidence_collected', 'Vendor invoice documents and mailbox archive collected for review.', 'evidence', 6, '2026-01-05 13:00:00', 4),
    (1, 'custody_transfer', 'All seized devices received into the Regional Forensics Lab evidence queue.', 'chain_of_custody', NULL, '2026-01-05 15:00:00', 2),
    (1, 'examination_started', 'Static analysis of the finance manager''s laptop disk image began.', 'evidence_examinations', 2, '2026-01-06 11:00:00', 2),
    (1, 'examination_started', 'Mobile device forensic recovery began on the seized Galaxy S23.', 'evidence_examinations', 1, '2026-01-06 09:00:00', 2),
    (1, 'examination_completed', 'Recovered deleted messaging data referencing the flagged vendor account.', 'evidence_examinations', 1, '2026-01-06 15:00:00', 2),
    (1, 'examination_completed', 'Email timeline analysis corroborated fraudulent invoice submission dates.', 'evidence_examinations', 7, '2026-01-07 14:00:00', 2),
    (1, 'report_filed', 'Preliminary Forensic Findings report (RPT-2026-001) submitted for review.', 'forensic_reports', 1, '2026-01-07 09:00:00', 2),
    (1, 'report_filed', 'Device Examination Report (RPT-2026-002) submitted for review.', 'forensic_reports', 2, '2026-01-08 09:00:00', 2),
    (1, 'status_change', 'Case status updated to UNDER_INVESTIGATION following confirmation of fraudulent transfers.', 'cases', 1, '2026-01-08 11:00:00', 4),
    (1, 'report_filed', 'Vendor Correspondence and Email Timeline Analysis (RPT-2026-003) drafted.', 'forensic_reports', 3, '2026-01-09 09:00:00', 2),
    (1, 'other', 'Case Supervisor requested an extended review of the vendor cross-reference appendix.', 'forensic_reports', 1, '2026-01-09 12:00:00', 4),
    (2, 'case_opened', 'Case CASE-2026-002 opened after an overnight ransomware encryption event was detected.', 'cases', 2, '2026-01-11 09:00:00', 5),
    (2, 'evidence_collected', 'Order-management server and affected laptop imaged on-site.', 'devices', 5, '2026-01-11 11:00:00', 6),
    (2, 'evidence_collected', 'Full packet capture of the logistics network acquired.', 'evidence', 12, '2026-01-11 13:00:00', 5),
    (2, 'custody_transfer', 'Server disk image transported to the National Cyber Forensics Lab for priority analysis.', 'chain_of_custody', NULL, '2026-01-11 15:00:00', 6),
    (2, 'examination_started', 'Static analysis of the server disk image identified the ransomware binary.', 'evidence_examinations', 5, '2026-01-12 09:00:00', 6),
    (2, 'examination_completed', 'Memory analysis confirmed an active C2 connection at time of capture.', 'evidence_examinations', 6, '2026-01-12 19:00:00', 6),
    (2, 'examination_started', 'Deep packet inspection of the network capture began to trace data exfiltration.', 'evidence_examinations', 8, '2026-01-12 12:00:00', 5),
    (2, 'report_filed', 'Ransomware Incident Technical Report (RPT-2026-004) submitted for review.', 'forensic_reports', 4, '2026-01-13 09:00:00', 6),
    (2, 'report_filed', 'Network Traffic and Exfiltration Assessment (RPT-2026-005) submitted.', 'forensic_reports', 5, '2026-01-14 09:00:00', 5),
    (2, 'status_change', 'Priority escalated to CRITICAL following confirmation of a double-extortion threat.', 'cases', 2, '2026-01-11 17:00:00', 5),
    (3, 'case_opened', 'Case CASE-2026-003 opened following an internal alert on unusual database export volume.', 'cases', 3, '2025-11-26 09:00:00', 4),
    (3, 'evidence_collected', 'Workstation, USB drive, and external HDD seized from the administrator''s desk.', 'devices', 8, '2025-11-26 10:00:00', 4),
    (3, 'custody_transfer', 'Seized media received at the Regional Forensics Lab for imaging.', 'chain_of_custody', NULL, '2025-11-26 12:00:00', 9),
    (3, 'examination_started', 'Static analysis of the workstation disk image began.', 'evidence_examinations', 9, '2025-11-27 09:00:00', 9),
    (3, 'examination_completed', 'File access timestamps confirmed bulk database export activity pre-resignation.', 'evidence_examinations', 9, '2025-11-27 16:00:00', 9),
    (3, 'examination_completed', 'Deleted export archive recovered from unallocated space on the USB drive.', 'evidence_examinations', 11, '2025-11-28 09:00:00', 9),
    (3, 'report_filed', 'Data Exfiltration Findings Report (RPT-2026-006) finalized.', 'forensic_reports', 6, '2025-11-29 09:00:00', 9),
    (3, 'report_filed', 'USB Media Recovery and Timeline Report (RPT-2026-007) approved.', 'forensic_reports', 7, '2025-11-30 09:00:00', 9),
    (3, 'status_change', 'Case status updated to CLOSED following approval of the final findings report.', 'cases', 3, '2026-01-02 09:00:00', 4),
    (3, 'case_closed', 'Case CASE-2026-003 formally closed; devices released back to the organization.', 'cases', 3, '2026-01-02 09:00:00', 4),
    (4, 'case_opened', 'Case CASE-2026-004 opened after a reported fraudulent payment redirection attempt.', 'cases', 4, '2026-01-15 09:00:00', 10),
    (4, 'evidence_collected', 'Suspect''s phone, laptop, and tablet seized following identification of the sender.', 'devices', 11, '2026-01-15 10:00:00', 10),
    (4, 'evidence_collected', 'Printed phishing email and network capture from the finance office collected.', 'evidence', 25, '2026-01-15 12:00:00', 3),
    (4, 'custody_transfer', 'Mobile device received at the Regional Forensics Lab for extraction.', 'chain_of_custody', NULL, '2026-01-15 12:00:00', 3),
    (4, 'examination_started', 'Mobile extraction of the suspect''s iPhone 13 began.', 'evidence_examinations', 12, '2026-01-16 09:00:00', 3),
    (4, 'examination_completed', 'Sent-message history confirmed the phishing email was composed on this device.', 'evidence_examinations', 12, '2026-01-16 14:00:00', 3),
    (4, 'examination_completed', 'Traffic capture confirmed credential submission to the spoofed payment portal.', 'evidence_examinations', 20, '2026-01-17 13:00:00', 3),
    (4, 'report_filed', 'Phishing Campaign Technical Findings (RPT-2026-008) submitted for review.', 'forensic_reports', 8, '2026-01-17 09:00:00', 3),
    (4, 'report_filed', 'Mobile Device Extraction Summary (RPT-2026-009) submitted.', 'forensic_reports', 9, '2026-01-18 09:00:00', 3),
    (4, 'other', 'Legal & Compliance Unit requested a supplementary browser-cache analysis.', 'evidence_examinations', 15, '2026-01-18 11:00:00', 10),
    (5, 'case_opened', 'Case CASE-2026-005 opened after the victim reported an unauthorized wallet drain.', 'cases', 5, '2025-10-27 09:00:00', 1),
    (5, 'evidence_collected', 'Victim''s phone and laptop voluntarily surrendered for imaging.', 'devices', 14, '2025-10-27 10:00:00', 1),
    (5, 'custody_transfer', 'Laptop disk image received at the Southern Digital Forensics Lab.', 'chain_of_custody', NULL, '2025-10-27 12:00:00', 7),
    (5, 'examination_started', 'Recovery of wallet application session data began on the mobile backup.', 'evidence_examinations', 17, '2025-10-28 09:00:00', 1),
    (5, 'examination_completed', 'Unencrypted notes file containing the wallet seed phrase was located.', 'evidence_examinations', 18, '2025-10-28 18:00:00', 7),
    (5, 'examination_completed', 'Memory artifacts consistent with clipboard-hijacking malware identified.', 'evidence_examinations', 19, '2025-10-28 15:00:00', 7),
    (5, 'report_filed', 'Cryptocurrency Wallet Theft Final Report (RPT-2026-010) finalized.', 'forensic_reports', 10, '2025-12-11 09:00:00', 1),
    (5, 'status_change', 'Case status updated to ARCHIVED after final report issuance and device return.', 'cases', 5, '2025-12-16 09:00:00', 1),
    (5, 'case_closed', 'Case CASE-2026-005 archived; no further recovery action pursued by the victim.', 'cases', 5, '2025-12-16 09:00:00', 1),
    (5, 'other', 'Blockchain analytics vendor report attached confirming the destination wallet cluster.', 'evidence', 29, '2025-12-12 09:00:00', 1);

-- =====================================================================
-- 21. audit_logs
-- =====================================================================
INSERT INTO audit_logs (user_id, table_name, record_id, action_type, old_values, new_values, action_timestamp, ip_address) VALUES
    (1, 'cases', 1, 'UPDATE', '{"status": "open"}', '{"status": "under_investigation"}', '2025-10-22 09:00:00', '10.12.4.21'),
    (2, 'cases', 2, 'UPDATE', '{"priority": "medium"}', '{"priority": "high"}', '2025-10-22 18:00:00', '10.12.4.22'),
    (3, 'evidence', 3, 'INSERT', NULL, '{"integrity_status": "intact"}', '2025-10-23 03:00:00', '10.12.4.23'),
    (4, 'evidence', 4, 'UPDATE', '{"integrity_status": "intact"}', '{"integrity_status": "under_verification"}', '2025-10-23 12:00:00', '10.12.5.10'),
    (5, 'devices', 5, 'UPDATE', '{"device_status": "seized"}', '{"device_status": "in_lab"}', '2025-10-23 21:00:00', '10.12.5.11'),
    (6, 'devices', 6, 'UPDATE', '{"device_status": "in_lab"}', '{"device_status": "under_examination"}', '2025-10-24 06:00:00', '192.168.20.14'),
    (7, 'chain_of_custody', 7, 'INSERT', NULL, '{"custody_action": "received"}', '2025-10-24 15:00:00', '192.168.20.15'),
    (8, 'evidence_examinations', 8, 'UPDATE', '{"examination_status": "scheduled"}', '{"examination_status": "in_progress"}', '2025-10-25 00:00:00', '192.168.20.16'),
    (9, 'evidence_examinations', 9, 'UPDATE', '{"examination_status": "in_progress"}', '{"examination_status": "completed"}', '2025-10-25 09:00:00', '172.16.8.5'),
    (10, 'forensic_reports', 10, 'UPDATE', '{"report_status": "draft"}', '{"report_status": "submitted"}', '2025-10-25 18:00:00', '172.16.8.6'),
    (1, 'forensic_reports', 1, 'UPDATE', '{"report_status": "submitted"}', '{"report_status": "under_review"}', '2025-10-26 03:00:00', '10.12.4.21'),
    (2, 'report_versions', 12, 'INSERT', NULL, '{"version_number": 1}', '2025-10-26 12:00:00', '10.12.4.22'),
    (3, 'case_investigators', 2, 'INSERT', NULL, '{"role_in_case": "forensic_analyst"}', '2025-10-26 21:00:00', '10.12.4.23'),
    (4, 'case_persons', 1, 'INSERT', NULL, '{"person_role": "witness"}', '2025-10-27 06:00:00', '10.12.5.10'),
    (5, 'users', 5, 'UPDATE', '{"last_login_at": null}', '{"last_login_at": "login_recorded"}', '2025-10-27 15:00:00', '10.12.5.11'),
    (6, 'evidence_hashes', 16, 'INSERT', NULL, '{"hash_algorithm": "SHA256"}', '2025-10-28 00:00:00', '192.168.20.14'),
    (7, 'case_timeline', 17, 'INSERT', NULL, '{"event_type": "status_change"}', '2025-10-28 09:00:00', '192.168.20.15'),
    (8, 'cases', 3, 'UPDATE', '{"status": "under_investigation"}', '{"status": "pending_review"}', '2025-10-28 18:00:00', '192.168.20.16'),
    (9, 'evidence', 19, 'UPDATE', '{"storage_location_id": 2}', '{"storage_location_id": 8}', '2025-10-29 03:00:00', '172.16.8.5'),
    (10, 'devices', 5, 'UPDATE', '{"current_location_id": 3}', '{"current_location_id": 2}', '2025-10-29 12:00:00', '172.16.8.6'),
    (1, 'cases', 1, 'UPDATE', '{"status": "open"}', '{"status": "under_investigation"}', '2025-10-29 21:00:00', '10.12.4.21'),
    (2, 'cases', 2, 'UPDATE', '{"priority": "medium"}', '{"priority": "high"}', '2025-10-30 06:00:00', '10.12.4.22'),
    (3, 'evidence', 23, 'INSERT', NULL, '{"integrity_status": "intact"}', '2025-10-30 15:00:00', '10.12.4.23'),
    (4, 'evidence', 24, 'UPDATE', '{"integrity_status": "intact"}', '{"integrity_status": "under_verification"}', '2025-10-31 00:00:00', '10.12.5.10'),
    (5, 'devices', 10, 'UPDATE', '{"device_status": "seized"}', '{"device_status": "in_lab"}', '2025-10-31 09:00:00', '10.12.5.11'),
    (6, 'devices', 11, 'UPDATE', '{"device_status": "in_lab"}', '{"device_status": "under_examination"}', '2025-10-31 18:00:00', '192.168.20.14'),
    (7, 'chain_of_custody', 27, 'INSERT', NULL, '{"custody_action": "received"}', '2025-11-01 03:00:00', '192.168.20.15'),
    (8, 'evidence_examinations', 8, 'UPDATE', '{"examination_status": "scheduled"}', '{"examination_status": "in_progress"}', '2025-11-01 12:00:00', '192.168.20.16'),
    (9, 'evidence_examinations', 9, 'UPDATE', '{"examination_status": "in_progress"}', '{"examination_status": "completed"}', '2025-11-01 21:00:00', '172.16.8.5'),
    (10, 'forensic_reports', 10, 'UPDATE', '{"report_status": "draft"}', '{"report_status": "submitted"}', '2025-11-02 06:00:00', '172.16.8.6'),
    (1, 'forensic_reports', 1, 'UPDATE', '{"report_status": "submitted"}', '{"report_status": "under_review"}', '2025-11-02 15:00:00', '10.12.4.21'),
    (2, 'report_versions', 4, 'INSERT', NULL, '{"version_number": 1}', '2025-11-03 00:00:00', '10.12.4.22'),
    (3, 'case_investigators', 11, 'INSERT', NULL, '{"role_in_case": "forensic_analyst"}', '2025-11-03 09:00:00', '10.12.4.23'),
    (4, 'case_persons', 8, 'INSERT', NULL, '{"person_role": "witness"}', '2025-11-03 18:00:00', '10.12.5.10'),
    (5, 'users', 5, 'UPDATE', '{"last_login_at": null}', '{"last_login_at": "login_recorded"}', '2025-11-04 03:00:00', '10.12.5.11'),
    (6, 'evidence_hashes', 36, 'INSERT', NULL, '{"hash_algorithm": "SHA256"}', '2025-11-04 12:00:00', '192.168.20.14'),
    (7, 'case_timeline', 37, 'INSERT', NULL, '{"event_type": "status_change"}', '2025-11-04 21:00:00', '192.168.20.15'),
    (8, 'cases', 3, 'UPDATE', '{"status": "under_investigation"}', '{"status": "pending_review"}', '2025-11-05 06:00:00', '192.168.20.16'),
    (9, 'evidence', 9, 'UPDATE', '{"storage_location_id": 2}', '{"storage_location_id": 8}', '2025-11-05 15:00:00', '172.16.8.5'),
    (10, 'devices', 10, 'UPDATE', '{"current_location_id": 3}', '{"current_location_id": 2}', '2025-11-06 00:00:00', '172.16.8.6'),
    (1, 'cases', 1, 'UPDATE', '{"status": "open"}', '{"status": "under_investigation"}', '2025-11-06 09:00:00', '10.12.4.21'),
    (2, 'cases', 2, 'UPDATE', '{"priority": "medium"}', '{"priority": "high"}', '2025-11-06 18:00:00', '10.12.4.22'),
    (3, 'evidence', 13, 'INSERT', NULL, '{"integrity_status": "intact"}', '2025-11-07 03:00:00', '10.12.4.23'),
    (4, 'evidence', 14, 'UPDATE', '{"integrity_status": "intact"}', '{"integrity_status": "under_verification"}', '2025-11-07 12:00:00', '10.12.5.10'),
    (5, 'devices', 15, 'UPDATE', '{"device_status": "seized"}', '{"device_status": "in_lab"}', '2025-11-07 21:00:00', '10.12.5.11'),
    (6, 'devices', 1, 'UPDATE', '{"device_status": "in_lab"}', '{"device_status": "under_examination"}', '2025-11-08 06:00:00', '192.168.20.14'),
    (7, 'chain_of_custody', 47, 'INSERT', NULL, '{"custody_action": "received"}', '2025-11-08 15:00:00', '192.168.20.15'),
    (8, 'evidence_examinations', 8, 'UPDATE', '{"examination_status": "scheduled"}', '{"examination_status": "in_progress"}', '2025-11-09 00:00:00', '192.168.20.16'),
    (9, 'evidence_examinations', 9, 'UPDATE', '{"examination_status": "in_progress"}', '{"examination_status": "completed"}', '2025-11-09 09:00:00', '172.16.8.5'),
    (10, 'forensic_reports', 10, 'UPDATE', '{"report_status": "draft"}', '{"report_status": "submitted"}', '2025-11-09 18:00:00', '172.16.8.6'),
    (1, 'forensic_reports', 1, 'UPDATE', '{"report_status": "submitted"}', '{"report_status": "under_review"}', '2025-11-10 03:00:00', '10.12.4.21'),
    (2, 'report_versions', 10, 'INSERT', NULL, '{"version_number": 1}', '2025-11-10 12:00:00', '10.12.4.22'),
    (3, 'case_investigators', 9, 'INSERT', NULL, '{"role_in_case": "forensic_analyst"}', '2025-11-10 21:00:00', '10.12.4.23'),
    (4, 'case_persons', 2, 'INSERT', NULL, '{"person_role": "witness"}', '2025-11-11 06:00:00', '10.12.5.10'),
    (5, 'users', 5, 'UPDATE', '{"last_login_at": null}', '{"last_login_at": "login_recorded"}', '2025-11-11 15:00:00', '10.12.5.11'),
    (6, 'evidence_hashes', 18, 'INSERT', NULL, '{"hash_algorithm": "SHA256"}', '2025-11-12 00:00:00', '192.168.20.14'),
    (7, 'case_timeline', 3, 'INSERT', NULL, '{"event_type": "status_change"}', '2025-11-12 09:00:00', '192.168.20.15'),
    (8, 'cases', 3, 'UPDATE', '{"status": "under_investigation"}', '{"status": "pending_review"}', '2025-11-12 18:00:00', '192.168.20.16'),
    (9, 'evidence', 29, 'UPDATE', '{"storage_location_id": 2}', '{"storage_location_id": 8}', '2025-11-13 03:00:00', '172.16.8.5'),
    (10, 'devices', 15, 'UPDATE', '{"current_location_id": 3}', '{"current_location_id": 2}', '2025-11-13 12:00:00', '172.16.8.6'),
    (1, 'cases', 1, 'UPDATE', '{"status": "open"}', '{"status": "under_investigation"}', '2025-11-13 21:00:00', '10.12.4.21'),
    (2, 'cases', 2, 'UPDATE', '{"priority": "medium"}', '{"priority": "high"}', '2025-11-14 06:00:00', '10.12.4.22'),
    (3, 'evidence', 3, 'INSERT', NULL, '{"integrity_status": "intact"}', '2025-11-14 15:00:00', '10.12.4.23'),
    (4, 'evidence', 4, 'UPDATE', '{"integrity_status": "intact"}', '{"integrity_status": "under_verification"}', '2025-11-15 00:00:00', '10.12.5.10'),
    (5, 'devices', 5, 'UPDATE', '{"device_status": "seized"}', '{"device_status": "in_lab"}', '2025-11-15 09:00:00', '10.12.5.11'),
    (6, 'devices', 6, 'UPDATE', '{"device_status": "in_lab"}', '{"device_status": "under_examination"}', '2025-11-15 18:00:00', '192.168.20.14'),
    (7, 'chain_of_custody', 67, 'INSERT', NULL, '{"custody_action": "received"}', '2025-11-16 03:00:00', '192.168.20.15'),
    (8, 'evidence_examinations', 8, 'UPDATE', '{"examination_status": "scheduled"}', '{"examination_status": "in_progress"}', '2025-11-16 12:00:00', '192.168.20.16'),
    (9, 'evidence_examinations', 9, 'UPDATE', '{"examination_status": "in_progress"}', '{"examination_status": "completed"}', '2025-11-16 21:00:00', '172.16.8.5'),
    (10, 'forensic_reports', 10, 'UPDATE', '{"report_status": "draft"}', '{"report_status": "submitted"}', '2025-11-17 06:00:00', '172.16.8.6'),
    (1, 'forensic_reports', 1, 'UPDATE', '{"report_status": "submitted"}', '{"report_status": "under_review"}', '2025-11-17 15:00:00', '10.12.4.21'),
    (2, 'report_versions', 2, 'INSERT', NULL, '{"version_number": 1}', '2025-11-18 00:00:00', '10.12.4.22'),
    (3, 'case_investigators', 7, 'INSERT', NULL, '{"role_in_case": "forensic_analyst"}', '2025-11-18 09:00:00', '10.12.4.23'),
    (4, 'case_persons', 9, 'INSERT', NULL, '{"person_role": "witness"}', '2025-11-18 18:00:00', '10.12.5.10'),
    (5, 'users', 5, 'UPDATE', '{"last_login_at": null}', '{"last_login_at": "login_recorded"}', '2025-11-19 03:00:00', '10.12.5.11'),
    (6, 'evidence_hashes', 38, 'INSERT', NULL, '{"hash_algorithm": "SHA256"}', '2025-11-19 12:00:00', '192.168.20.14'),
    (7, 'case_timeline', 23, 'INSERT', NULL, '{"event_type": "status_change"}', '2025-11-19 21:00:00', '192.168.20.15'),
    (8, 'cases', 3, 'UPDATE', '{"status": "under_investigation"}', '{"status": "pending_review"}', '2025-11-20 06:00:00', '192.168.20.16'),
    (9, 'evidence', 19, 'UPDATE', '{"storage_location_id": 2}', '{"storage_location_id": 8}', '2025-11-20 15:00:00', '172.16.8.5'),
    (10, 'devices', 5, 'UPDATE', '{"current_location_id": 3}', '{"current_location_id": 2}', '2025-11-21 00:00:00', '172.16.8.6'),
    (1, 'cases', 1, 'UPDATE', '{"status": "open"}', '{"status": "under_investigation"}', '2025-11-21 09:00:00', '10.12.4.21'),
    (2, 'cases', 2, 'UPDATE', '{"priority": "medium"}', '{"priority": "high"}', '2025-11-21 18:00:00', '10.12.4.22'),
    (3, 'evidence', 23, 'INSERT', NULL, '{"integrity_status": "intact"}', '2025-11-22 03:00:00', '10.12.4.23'),
    (4, 'evidence', 24, 'UPDATE', '{"integrity_status": "intact"}', '{"integrity_status": "under_verification"}', '2025-11-22 12:00:00', '10.12.5.10'),
    (5, 'devices', 10, 'UPDATE', '{"device_status": "seized"}', '{"device_status": "in_lab"}', '2025-11-22 21:00:00', '10.12.5.11'),
    (6, 'devices', 11, 'UPDATE', '{"device_status": "in_lab"}', '{"device_status": "under_examination"}', '2025-11-23 06:00:00', '192.168.20.14'),
    (7, 'chain_of_custody', 11, 'INSERT', NULL, '{"custody_action": "received"}', '2025-11-23 15:00:00', '192.168.20.15'),
    (8, 'evidence_examinations', 8, 'UPDATE', '{"examination_status": "scheduled"}', '{"examination_status": "in_progress"}', '2025-11-24 00:00:00', '192.168.20.16'),
    (9, 'evidence_examinations', 9, 'UPDATE', '{"examination_status": "in_progress"}', '{"examination_status": "completed"}', '2025-11-24 09:00:00', '172.16.8.5'),
    (10, 'forensic_reports', 10, 'UPDATE', '{"report_status": "draft"}', '{"report_status": "submitted"}', '2025-11-24 18:00:00', '172.16.8.6'),
    (NULL, 'forensic_reports', 1, 'UPDATE', '{"note": "system_maintenance"}', '{"note": "system_maintenance_complete"}', '2025-11-25 03:00:00', NULL),
    (NULL, 'report_versions', 8, 'UPDATE', '{"note": "system_maintenance"}', '{"note": "system_maintenance_complete"}', '2025-11-25 12:00:00', NULL),
    (NULL, 'case_investigators', 5, 'UPDATE', '{"note": "system_maintenance"}', '{"note": "system_maintenance_complete"}', '2025-11-25 21:00:00', NULL),
    (NULL, 'case_persons', 3, 'UPDATE', '{"note": "system_maintenance"}', '{"note": "system_maintenance_complete"}', '2025-11-26 06:00:00', NULL),
    (NULL, 'users', 5, 'UPDATE', '{"note": "system_maintenance"}', '{"note": "system_maintenance_complete"}', '2025-11-26 15:00:00', NULL),
    (6, 'evidence_hashes', 20, 'INSERT', NULL, '{"hash_algorithm": "SHA256"}', '2025-11-27 00:00:00', '192.168.20.14'),
    (7, 'case_timeline', 43, 'INSERT', NULL, '{"event_type": "status_change"}', '2025-11-27 09:00:00', '192.168.20.15'),
    (8, 'cases', 3, 'UPDATE', '{"status": "under_investigation"}', '{"status": "pending_review"}', '2025-11-27 18:00:00', '192.168.20.16'),
    (9, 'evidence', 9, 'UPDATE', '{"storage_location_id": 2}', '{"storage_location_id": 8}', '2025-11-28 03:00:00', '172.16.8.5'),
    (10, 'devices', 10, 'UPDATE', '{"current_location_id": 3}', '{"current_location_id": 2}', '2025-11-28 12:00:00', '172.16.8.6');

COMMIT;

SELECT 'FORGE-X seed data loaded successfully.' AS status;
