#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
FORGE-X seed-data generator.
Deterministic (no randomness) — builds a fully self-consistent dataset
by tracking auto-increment IDs explicitly in Python before emitting SQL.
"""
from datetime import datetime, timedelta

OUT = []
def emit(sql):
    OUT.append(sql.rstrip())

def sql_str(s):
    if s is None:
        return "NULL"
    return "'" + s.replace("'", "''") + "'"

def sql_val(v):
    if v is None:
        return "NULL"
    if isinstance(v, str):
        return sql_str(v)
    if isinstance(v, datetime):
        return "'" + v.strftime("%Y-%m-%d %H:%M:%S") + "'"
    return str(v)

def insert(table, columns, rows):
    """rows: list of tuples matching columns order"""
    emit(f"INSERT INTO {table} ({', '.join(columns)}) VALUES")
    lines = []
    for row in rows:
        vals = ", ".join(sql_val(v) for v in row)
        lines.append(f"    ({vals})")
    emit(",\n".join(lines) + ";")
    emit("")

D0 = datetime(2026, 1, 5, 9, 0, 0)  # base epoch for the whole dataset

# =====================================================================
# HEADER
# =====================================================================
emit("""-- =====================================================================
-- FORGE-X : Forensic Operations, Records, Governance & Evidence Exchange
-- File   : 09_seed_data.sql
-- Purpose: Realistic, fully self-consistent demo/test dataset covering
--          every table and the complete evidence lifecycle, including a
--          flagship case (CASE-2026-001) with rich narrative detail.
-- Depends: 01_create_database.sql, 02_tables.sql, 03_constraints.sql,
--          04_indexes.sql must already have run.
--
-- GENERATION METHOD
--   This file was generated by a small deterministic Python script
--   (scripts/generate_seed_data.py) rather than typed by hand, so that
--   ~450+ rows across 21 interdependent tables stay perfectly
--   referentially consistent (every FK value is guaranteed to exist)
--   while still reading as realistic, narratively coherent case data —
--   not Lorem-Ipsum filler. No randomness is used: every value is
--   picked deterministically from realistic-but-fictional pools, so
--   the output is 100% reproducible.
--
-- FICTIONAL DATA NOTICE
--   All names, badge numbers, national ID numbers, IP addresses, device
--   serials/IMEIs, and case content below are entirely fictional and
--   were constructed for this demo. No real person's data is used.
-- =====================================================================

USE forge_x;

-- Defensive: ensures THIS session sends/receives utf8mb4 regardless of
-- how the client was invoked (protects against a classic gotcha: running
-- `mysql -u root < this_file.sql` without --default-character-set=utf8mb4
-- silently corrupts any non-ASCII literal in this file via latin1
-- misinterpretation at write time -- discovered and fixed during Step 6
-- backend integration testing).
SET NAMES utf8mb4;

SET SESSION sql_mode = 'STRICT_ALL_TABLES,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
SET time_zone = '+00:00';

START TRANSACTION;
""")

# =====================================================================
# 1. roles
# =====================================================================
emit("-- =====================================================================")
emit("-- 1. roles")
emit("-- =====================================================================")
roles = [
    ("ADMIN", "Full system access; manages users, roles, and departments"),
    ("LEAD_INVESTIGATOR", "Owns and directs cases end-to-end: cases, investigators, persons, devices, evidence, reports"),
    ("INVESTIGATOR", "Works assigned cases: assigned cases (read), evidence, and case timeline"),
    ("FORENSIC_ANALYST", "Performs technical examination of evidence: evidence, examinations, reports"),
    ("EVIDENCE_CUSTODIAN", "Manages physical custody hand-offs: evidence custody transfers"),
    ("VIEWER", "Read-only access across the system; no write permissions anywhere"),
]
insert("roles", ["role_name", "role_description"], roles)
# role_id: 1 ADMIN, 2 LEAD_INVESTIGATOR, 3 INVESTIGATOR, 4 FORENSIC_ANALYST, 5 EVIDENCE_CUSTODIAN, 6 VIEWER

# =====================================================================
# 2. departments
# =====================================================================
emit("-- =====================================================================")
emit("-- 2. departments")
emit("-- =====================================================================")
departments = [
    ("Cyber Crime Cell", "CCC"),
    ("Digital Forensics Lab", "DFL"),
    ("IT Security Division", "ITSD"),
    ("Legal & Compliance Unit", "LCU"),
]
insert("departments", ["department_name", "department_code"], departments)
# department_id: 1 CCC, 2 DFL, 3 ITSD, 4 LCU

# =====================================================================
# 3. locations
# =====================================================================
emit("-- =====================================================================")
emit("-- 3. locations")
emit("-- =====================================================================")
locations = [
    ("Central Evidence Locker", "evidence_locker", "MG Road Annex, Building C", "Pune", "Maharashtra", "411001"),
    ("Regional Forensics Lab", "lab", "Hinjewadi IT Park, Phase 2", "Pune", "Maharashtra", "411057"),
    ("State Cyber Cell Headquarters", "field_site", "Bandra-Kurla Complex", "Mumbai", "Maharashtra", "400051"),
    ("Metro Evidence Storage Facility", "storage_facility", "Andheri East Industrial Estate", "Mumbai", "Maharashtra", "400093"),
    ("Southern Digital Forensics Lab", "lab", "Electronic City Phase 1", "Bengaluru", "Karnataka", "560100"),
    ("District Court Complex", "court", "Shivajinagar Court Road", "Pune", "Maharashtra", "411005"),
    ("Eastern Zone Evidence Locker", "evidence_locker", "Hitech City Road", "Hyderabad", "Telangana", "500081"),
    ("National Cyber Forensics Lab", "lab", "Dwarka Sector 10", "Delhi", "Delhi", "110075"),
]
insert("locations", ["location_name", "location_type", "address_line", "city", "state", "postal_code"], locations)
# location_id: 1 Central Evidence Locker(Pune) 2 Regional Forensics Lab(Pune) 3 State Cyber Cell HQ(Mumbai)
# 4 Metro Evidence Storage(Mumbai) 5 Southern Digital Forensics Lab(Bengaluru) 6 District Court(Pune)
# 7 Eastern Zone Evidence Locker(Hyderabad) 8 National Cyber Forensics Lab(Delhi)

# =====================================================================
# 4. case_types
# =====================================================================
emit("-- =====================================================================")
emit("-- 4. case_types")
emit("-- =====================================================================")
case_types = [
    ("Cybercrime", "Offenses committed using computer networks or digital devices as the primary vector"),
    ("Data Breach", "Unauthorized access to or exfiltration of confidential/sensitive data"),
    ("Fraud", "Financial or corporate fraud with a digital evidence component"),
    ("Malware Incident", "Ransomware, worms, trojans, or other malicious-software incidents"),
    ("Intellectual Property Theft", "Theft or unauthorized use of proprietary digital assets"),
]
insert("case_types", ["type_name", "type_description"], case_types)
# case_type_id: 1 Cybercrime 2 Data Breach 3 Fraud 4 Malware Incident 5 IP Theft

# =====================================================================
# 5. device_types
# =====================================================================
emit("-- =====================================================================")
emit("-- 5. device_types")
emit("-- =====================================================================")
device_types = [
    ("Smartphone", "Mobile handset (Android/iOS)"),
    ("Laptop", "Portable personal computer"),
    ("Desktop Computer", "Fixed workstation/personal computer"),
    ("External Hard Disk Drive", "Portable external storage drive"),
    ("USB Flash Drive", "Removable USB flash/thumb drive"),
    ("Server", "Rack or standalone server hardware"),
    ("Network Router", "Network routing/switching hardware"),
    ("Tablet", "Tablet-class mobile device"),
]
insert("device_types", ["type_name", "type_description"], device_types)
# device_type_id: 1 Smartphone 2 Laptop 3 Desktop 4 External HDD 5 USB Flash Drive 6 Server 7 Router 8 Tablet

# =====================================================================
# 6. evidence_types
# =====================================================================
emit("-- =====================================================================")
emit("-- 6. evidence_types")
emit("-- =====================================================================")
evidence_types = [
    ("Disk Image", "Bit-for-bit forensic image of a storage medium"),
    ("Memory Dump", "Captured volatile RAM snapshot"),
    ("Log File", "System, application, or network log extract"),
    ("Photograph", "Photographic documentation of physical evidence or a scene"),
    ("Document Scan", "Scanned physical or digitally-native document"),
    ("Network Capture", "Captured network traffic (PCAP)"),
    ("Email Archive", "Exported email mailbox or message archive"),
    ("Mobile Device Backup", "Full or partial backup extracted from a mobile device"),
]
insert("evidence_types", ["type_name", "type_description"], evidence_types)
# evidence_type_id: 1 Disk Image 2 Memory Dump 3 Log File 4 Photograph 5 Document Scan
#                   6 Network Capture 7 Email Archive 8 Mobile Backup

# =====================================================================
# 7. forensic_tools
# =====================================================================
emit("-- =====================================================================")
emit("-- 7. forensic_tools")
emit("-- =====================================================================")
tools = [
    ("Autopsy", "Basis Technology", "4.21", "open_source"),
    ("EnCase Forensic", "OpenText", "24.1", "commercial"),
    ("FTK (Forensic Toolkit)", "Exterro", "7.6", "commercial"),
    ("Wireshark", "Wireshark Foundation", "4.2", "open_source"),
    ("Volatility 3", "Volatility Foundation", "2.5", "open_source"),
    ("Cellebrite UFED", "Cellebrite", "7.60", "commercial"),
    ("X-Ways Forensics", "X-Ways Software Technology", "20.9", "commercial"),
    ("Magnet AXIOM", "Magnet Forensics", "7.5", "commercial"),
]
insert("forensic_tools", ["tool_name", "vendor", "version", "license_type"], tools)
# tool_id: 1 Autopsy 2 EnCase 3 FTK 4 Wireshark 5 Volatility3 6 Cellebrite UFED 7 X-Ways 8 Magnet AXIOM

print("Part 1 (lookups) generated:", len(OUT), "statements so far")
with open("/home/claude/seedgen/part1.sql", "w") as f:
    f.write("\n".join(OUT))

# =====================================================================
# 8. users (10)
# =====================================================================
emit("-- =====================================================================")
emit("-- 8. users")
emit("-- =====================================================================")
# (badge, username, email, full_name, role_id, department_id, phone)
users = [
    ("FX-B-1001", "asharma", "a.sharma@forgex.gov.in", "Ananya Sharma", 2, 1, "+91-98220-11001"),   # LEAD_INVESTIGATOR
    ("FX-B-1002", "rverma",  "r.verma@forgex.gov.in",  "Rohan Verma",   4, 2, "+91-98220-11002"),   # FORENSIC_ANALYST
    ("FX-B-1003", "pnair",   "p.nair@forgex.gov.in",   "Priya Nair",    4, 2, "+91-98220-11003"),   # FORENSIC_ANALYST
    ("FX-B-1004", "kiyer",   "k.iyer@forgex.gov.in",   "Karthik Iyer",  2, 1, "+91-98220-11004"),   # LEAD_INVESTIGATOR
    ("FX-B-1005", "mjoshi",  "m.joshi@forgex.gov.in",  "Meera Joshi",   2, 3, "+91-98220-11005"),   # LEAD_INVESTIGATOR
    ("FX-B-1006", "areddy",  "a.reddy@forgex.gov.in",  "Arjun Reddy",   3, 2, "+91-98220-11006"),   # INVESTIGATOR
    ("FX-B-1007", "dmenon",  "d.menon@forgex.gov.in",  "Divya Menon",   6, 4, "+91-98220-11007"),   # VIEWER
    ("FX-B-1008", "srao",    "s.rao@forgex.gov.in",    "Siddharth Rao", 1, 1, "+91-98220-11008"),   # ADMIN
    ("FX-B-1009", "nkulkarni","n.kulkarni@forgex.gov.in","Neha Kulkarni",5, 3, "+91-98220-11009"),   # EVIDENCE_CUSTODIAN
    ("FX-B-1010", "vsingh",  "v.singh@forgex.gov.in",  "Vikram Singh",  3, 1, "+91-98220-11010"),   # INVESTIGATOR
]
BCRYPT_STUB = "$2b$12$ForgeXDemoOnlyNotARealBcryptHashPlaceholder1234567890"[:60]
rows = [(b, u, e, BCRYPT_STUB, fn, r, d, ph) for (b,u,e,fn,r,d,ph) in users]
insert("users", ["badge_number","username","email","password_hash","full_name","role_id","department_id","phone_number"], rows)
# user_id 1..10 in the order above:
# 1 Ananya Sharma  2 Rohan Verma  3 Priya Nair  4 Karthik Iyer  5 Meera Joshi
# 6 Arjun Reddy    7 Divya Menon  8 Siddharth Rao 9 Neha Kulkarni 10 Vikram Singh

# =====================================================================
# 9. persons (10)
# =====================================================================
emit("-- =====================================================================")
emit("-- 9. persons")
emit("-- =====================================================================")
persons = [
    ("Ramesh", "Chandran", "1982-03-14", "NID-FX-770001", "male",   "+91-90110-22001", "ramesh.chandran@examplemail.test"),
    ("Sunita", "Deshmukh", "1979-11-02", "NID-FX-770002", "female", "+91-90110-22002", "sunita.deshmukh@examplemail.test"),
    ("Alok",   "Bhattacharya", "1990-06-21", None,         "male",   "+91-90110-22003", "alok.bhattacharya@examplemail.test"),
    ("Farhan", "Sheikh", "1985-01-09", "NID-FX-770004", "male",   "+91-90110-22004", "farhan.sheikh@examplemail.test"),
    ("Kavita", "Menon", "1993-09-30", None,               "female", "+91-90110-22005", "kavita.menon@examplemail.test"),
    ("Nikhil", "Agarwal", "1988-04-17", "NID-FX-770006", "male",   "+91-90110-22006", "nikhil.agarwal@examplemail.test"),
    ("Rajesh", "Pillai", "1976-12-25", "NID-FX-770007", "male",   "+91-90110-22007", "rajesh.pillai@examplemail.test"),
    ("Sanjana","Rao", "1991-07-08", None,                 "female", "+91-90110-22008", "sanjana.rao@examplemail.test"),
    ("Imran",  "Qureshi", "1987-02-19", "NID-FX-770009", "male",   "+91-90110-22009", "imran.qureshi@examplemail.test"),
    ("Deepa",  "Krishnan", "1994-05-27", "NID-FX-770010", "female", "+91-90110-22010", "deepa.krishnan@examplemail.test"),
]
insert("persons", ["first_name","last_name","date_of_birth","national_id_number","gender","phone_number","email"], persons)
# person_id 1..10:
# 1 Ramesh Chandran 2 Sunita Deshmukh 3 Alok Bhattacharya 4 Farhan Sheikh 5 Kavita Menon
# 6 Nikhil Agarwal 7 Rajesh Pillai 8 Sanjana Rao 9 Imran Qureshi 10 Deepa Krishnan

print("Part 2 (users, persons) generated:", len(OUT), "statements so far")
with open("/home/claude/seedgen/part2.sql", "w") as f:
    f.write("\n".join(OUT))

# =====================================================================
# 10. cases (5) — CASE-2026-001 is the flagship
# =====================================================================
emit("-- =====================================================================")
emit("-- 10. cases")
emit("-- =====================================================================")
# (case_number, case_title, case_type_id, status, priority, jurisdiction_location_id,
#  description, opened_at, closed_at, created_by)
cases = [
    ("CASE-2026-001", "Corporate Cyber Fraud Investigation", 3, "under_investigation", "high", 3,
     "Suspected internal financial fraud at a mid-sized manufacturing firm, involving falsified "
     "vendor invoices and unauthorized fund transfers routed through compromised finance-department "
     "workstations.", D0, None, 1),
    ("CASE-2026-002", "Ransomware Attack on Regional Logistics Network", 4, "open", "critical", 6,
     "A logistics company's order-management server and several workstations were encrypted "
     "overnight; a ransom note references a double-extortion threat to leak exfiltrated shipment data.",
     D0 + timedelta(days=6), None, 5),
    ("CASE-2026-003", "Data Exfiltration by Former IT Administrator", 2, "closed", "medium", 3,
     "A departing IT administrator is alleged to have copied customer databases to a personal "
     "external drive in the two weeks prior to resignation.", D0 - timedelta(days=40), D0 - timedelta(days=3), 4),
    ("CASE-2026-004", "Phishing Campaign Targeting Municipal Finance Office", 1, "pending_review", "medium", 6,
     "A spear-phishing email impersonating a vendor led to a municipal finance clerk disclosing "
     "portal credentials, resulting in a fraudulent payment redirection attempt.", D0 + timedelta(days=10), None, 10),
    ("CASE-2026-005", "Cryptocurrency Wallet Theft Investigation", 3, "archived", "low", 3,
     "A private individual's cryptocurrency wallet was drained following a compromised seed-phrase "
     "backup stored in an unencrypted note on a personal laptop.", D0 - timedelta(days=70), D0 - timedelta(days=20), 1),
]
rows = [(cn, ct, tid, st, pr, loc, desc, op, cl, cb) for (cn,ct,tid,st,pr,loc,desc,op,cl,cb) in cases]
insert("cases", ["case_number","case_title","case_type_id","status","priority",
                  "jurisdiction_location_id","description","opened_at","closed_at","created_by"], rows)
# case_id 1..5 = CASE-2026-001..005 in the order above

# =====================================================================
# 11. case_investigators
# =====================================================================
emit("-- =====================================================================")
emit("-- 11. case_investigators")
emit("-- =====================================================================")
# (case_id, user_id, role_in_case, assigned_at)
case_investigators = [
    (1, 1, "lead_investigator", D0),
    (1, 2, "forensic_analyst",  D0 + timedelta(hours=2)),
    (1, 4, "supervisor",        D0 + timedelta(hours=3)),
    (2, 5, "lead_investigator", D0 + timedelta(days=6)),
    (2, 6, "forensic_analyst",  D0 + timedelta(days=6, hours=1)),
    (3, 9, "forensic_analyst",  D0 - timedelta(days=40)),
    (3, 4, "supervisor",        D0 - timedelta(days=40, hours=-1)),
    (4, 10,"lead_investigator", D0 + timedelta(days=10)),
    (4, 3, "forensic_analyst",  D0 + timedelta(days=10, hours=2)),
    (5, 1, "lead_investigator", D0 - timedelta(days=70)),
    (5, 7, "consultant",        D0 - timedelta(days=69)),
]
insert("case_investigators", ["case_id","user_id","role_in_case","assigned_at"], case_investigators)

# =====================================================================
# 12. case_persons
# =====================================================================
emit("-- =====================================================================")
emit("-- 12. case_persons")
emit("-- =====================================================================")
# (case_id, person_id, person_role, notes, linked_at)
case_persons = [
    (1, 1, "suspect", "Finance department manager with approval access to the vendor-payment workflow.", D0 + timedelta(hours=4)),
    (1, 2, "person_of_interest", "External vendor contact flagged in multiple falsified invoices.", D0 + timedelta(hours=5)),
    (1, 3, "witness", "Junior accountant who first noticed the invoice discrepancies.", D0 + timedelta(hours=6)),
    (2, 6, "suspect", "Attribution under investigation via ransom-note communication channel.", D0 + timedelta(days=6, hours=2)),
    (2, 7, "victim", "IT operations head for the affected logistics firm.", D0 + timedelta(days=6, hours=3)),
    (2, 4, "witness", "Third-party contractor who observed unusual server activity before the incident.", D0 + timedelta(days=6, hours=4)),
    (3, 8, "suspect", "Departing IT administrator; resignation effective two weeks after alleged exfiltration.", D0 - timedelta(days=40, hours=-2)),
    (3, 3, "witness", "Colleague who noticed unusual after-hours database export activity.", D0 - timedelta(days=39)),
    (3, 5, "victim", "Data Protection Officer representing the affected customer database owner.", D0 - timedelta(days=38)),
    (4, 9, "suspect", "Sender of the spear-phishing email under investigation.", D0 + timedelta(days=10, hours=1)),
    (4, 5, "witness", "Municipal finance clerk who received and acted on the phishing email.", D0 + timedelta(days=10, hours=2)),
    (5, 10,"victim", "Wallet owner whose cryptocurrency holdings were drained.", D0 - timedelta(days=70, hours=-1)),
    (5, 2, "person_of_interest", "Contact linked to the destination wallet address in early tracing.", D0 - timedelta(days=69)),
]
insert("case_persons", ["case_id","person_id","person_role","notes","linked_at"], case_persons)

print("Part 3 (cases, junctions) generated:", len(OUT), "statements so far")
with open("/home/claude/seedgen/part3.sql", "w") as f:
    f.write("\n".join(OUT))

# =====================================================================
# 13. devices (15) — 4 for case1, 3/3/3/2 for cases 2-5
# =====================================================================
emit("-- =====================================================================")
emit("-- 13. devices")
emit("-- =====================================================================")
# (case_id, device_type_id, owner_person_id, serial_number, make, model, imei_number,
#  storage_capacity_gb, seized_at, seized_location_id, current_location_id, device_status)
devices = [
    # Case 1 — Corporate Cyber Fraud (devices 1-4)
    (1, 1, 1, "SNCF10021A", "Samsung", "Galaxy S23", "356123451234561", None, D0+timedelta(hours=1), 3, 2, "under_examination"),
    (1, 2, 1, "SNCF10022B", "Dell", "Latitude 5540", None, 512.00, D0+timedelta(hours=1), 3, 2, "under_examination"),
    (1, 3, 2, "SNCF10023C", "HP", "EliteDesk 800 G9", None, 1024.00, D0+timedelta(hours=2), 3, 2, "in_lab"),
    (1, 4, 3, "SNCF10024D", "Seagate", "Backup Plus 2TB", None, 2048.00, D0+timedelta(hours=2), 3, 2, "in_lab"),
    # Case 2 — Ransomware (devices 5-7)
    (2, 6, None, "SNRL20051X", "Dell", "PowerEdge R440", None, 4096.00, D0+timedelta(days=6, hours=1), 6, 5, "under_examination"),
    (2, 2, 7, "SNRL20052Y", "Lenovo", "ThinkPad T14", None, 512.00, D0+timedelta(days=6, hours=2), 6, 5, "in_lab"),
    (2, 7, None, "SNRL20053Z", "Cisco", "ISR 4331", None, None, D0+timedelta(days=6, hours=3), 6, 5, "seized"),
    # Case 3 — Data Exfiltration (devices 8-10)
    (3, 3, 8, "SNDE30081M", "Dell", "OptiPlex 7010", None, 1024.00, D0-timedelta(days=40)+timedelta(hours=1), 3, 1, "returned"),
    (3, 5, 8, "SNDE30082N", "SanDisk", "Ultra Dual Drive 128GB", None, 0.128, D0-timedelta(days=40)+timedelta(hours=1), 3, 1, "returned"),
    (3, 4, None, "SNDE30083P", "WD", "Elements 1TB", None, 1024.00, D0-timedelta(days=40)+timedelta(hours=2), 3, 1, "returned"),
    # Case 4 — Phishing (devices 11-13)
    (4, 1, 9, "SNPH40111Q", "Apple", "iPhone 13", "356123457654321", None, D0+timedelta(days=10, hours=1), 6, 2, "under_examination"),
    (4, 2, 9, "SNPH40112R", "HP", "ProBook 440 G9", None, 512.00, D0+timedelta(days=10, hours=1), 6, 2, "in_lab"),
    (4, 8, None, "SNPH40113S", "Samsung", "Galaxy Tab A8", "356123459998887", None, D0+timedelta(days=10, hours=2), 6, 2, "seized"),
    # Case 5 — Crypto Theft (devices 14-15)
    (5, 1, 10, "SNCT50141T", "Apple", "iPhone 12", "356123450001112", None, D0-timedelta(days=70)+timedelta(hours=1), 3, 1, "returned"),
    (5, 2, 10, "SNCT50142U", "Asus", "ZenBook 14", None, 512.00, D0-timedelta(days=70)+timedelta(hours=1), 3, 1, "returned"),
]
insert("devices", ["case_id","device_type_id","owner_person_id","serial_number","make","model",
                    "imei_number","storage_capacity_gb","seized_at","seized_location_id",
                    "current_location_id","device_status"], devices)
# device_id 1..15 in the order above

print("Part 4 (devices) generated:", len(OUT), "statements so far")
with open("/home/claude/seedgen/part4.sql", "w") as f:
    f.write("\n".join(OUT))

# =====================================================================
# 14. evidence (30) — 8 for case1 (flagship), 6/6/5/5 for cases 2-5
# =====================================================================
emit("-- =====================================================================")
emit("-- 14. evidence")
emit("-- =====================================================================")
# (evidence_number, case_id, device_id, evidence_type_id, description, file_path,
#  file_size_bytes, acquisition_method, collected_by, collected_at, storage_location_id, integrity_status)
def ev(num, case_id, device_id, etype, desc, fpath, fsize, method, collector, ts, storeloc, integrity="intact"):
    return (f"EVD-2026-{num:03d}", case_id, device_id, etype, desc, fpath, fsize, method, collector, ts, storeloc, integrity)

evidence = [
    # --- Case 1: CASE-2026-001 (flagship, 8 items) ---
    ev(1, 1, 1, 1, "Full physical disk image of the seized Samsung Galaxy S23 (SNCF10021A) belonging to suspect Ramesh Chandran.",
       "/evidence/case-001/EVD-2026-001.dd", 128849018880, "physical_extraction", 2, D0+timedelta(hours=2), 2),
    ev(2, 1, 2, 1, "Forensic disk image of the Dell Latitude 5540 laptop assigned to the finance department manager.",
       "/evidence/case-001/EVD-2026-002.E01", 549755813888, "physical_extraction", 2, D0+timedelta(hours=2,minutes=30), 2),
    ev(3, 1, 2, 2, "Live RAM capture taken from the Dell Latitude 5540 laptop prior to shutdown.",
       "/evidence/case-001/EVD-2026-003.mem", 17179869184, "logical_extraction", 2, D0+timedelta(hours=2,minutes=45), 2),
    ev(4, 1, 3, 3, "Extracted Windows Event Logs from the EliteDesk 800 workstation covering the fraud window.",
       "/evidence/case-001/EVD-2026-004-eventlogs.zip", 47185920, "logical_extraction", 1, D0+timedelta(hours=3), 2),
    ev(5, 1, None, 4, "Photographic documentation of the seizure scene at the finance department office.",
       "/evidence/case-001/EVD-2026-005-photos.zip", 62914560, "manual_documentation", 1, D0+timedelta(hours=1), 2),
    ev(6, 1, 4, 5, "Scanned set of falsified vendor invoices recovered from the external hard disk drive.",
       "/evidence/case-001/EVD-2026-006-invoices.pdf", 18874368, "manual_documentation", 4, D0+timedelta(hours=4), 2),
    ev(7, 1, 3, 7, "Exported Outlook mailbox archive from the EliteDesk workstation covering vendor correspondence.",
       "/evidence/case-001/EVD-2026-007-mailbox.pst", 2147483648, "logical_extraction", 2, D0+timedelta(hours=3,minutes=30), 2),
    ev(8, 1, None, 6, "Network traffic capture from the finance department VLAN during the suspected transfer window.",
       "/evidence/case-001/EVD-2026-008-capture.pcap", 314572800, "network_capture", 1, D0+timedelta(hours=5), 2),

    # --- Case 2: CASE-2026-002 (6 items) ---
    ev(9, 2, 5, 1, "Forensic image of the PowerEdge R440 order-management server disk array.",
       "/evidence/case-002/EVD-2026-009.E01", 2199023255552, "physical_extraction", 6, D0+timedelta(days=6,hours=2), 8),
    ev(10, 2, 5, 2, "RAM capture of the compromised order-management server prior to isolation.",
       "/evidence/case-002/EVD-2026-010.mem", 34359738368, "logical_extraction", 6, D0+timedelta(days=6,hours=2,minutes=15), 8, "under_verification"),
    ev(11, 2, 7, 3, "Router configuration and connection logs extracted from the Cisco ISR 4331.",
       "/evidence/case-002/EVD-2026-011-router.log", 8388608, "logical_extraction", 5, D0+timedelta(days=6,hours=3), 8),
    ev(12, 2, None, 6, "Full packet capture of the logistics network during the ransomware encryption event.",
       "/evidence/case-002/EVD-2026-012.pcap", 943718400, "network_capture", 5, D0+timedelta(days=6,hours=4), 8),
    ev(13, 2, 6, 1, "Disk image of the first workstation observed encrypted, belonging to the IT operations head.",
       "/evidence/case-002/EVD-2026-013.E01", 549755813888, "physical_extraction", 6, D0+timedelta(days=6,hours=2,minutes=30), 8),
    ev(14, 2, None, 5, "Scanned copy of the printed ransom note left on affected workstation desktops.",
       "/evidence/case-002/EVD-2026-014-ransomnote.pdf", 2097152, "manual_documentation", 5, D0+timedelta(days=6,hours=5), 8),

    # --- Case 3: CASE-2026-003 (6 items) ---
    ev(15, 3, 8, 1, "Disk image of the departing IT administrator's OptiPlex 7010 workstation.",
       "/evidence/case-003/EVD-2026-015.E01", 1099511627776, "physical_extraction", 9, D0-timedelta(days=40)+timedelta(hours=1), 2),
    ev(16, 3, 8, 3, "Database access and export logs recovered from the OptiPlex workstation.",
       "/evidence/case-003/EVD-2026-016-dblogs.zip", 15728640, "logical_extraction", 9, D0-timedelta(days=40)+timedelta(hours=1,minutes=30), 2),
    ev(17, 3, 9, 1, "Disk image of the SanDisk USB flash drive seized from the administrator's desk.",
       "/evidence/case-003/EVD-2026-017.dd", 128974848, "physical_extraction", 9, D0-timedelta(days=40)+timedelta(hours=2), 2, "compromised"),
    ev(18, 3, None, 5, "Scanned HR resignation and exit-interview paperwork referenced in the case timeline.",
       "/evidence/case-003/EVD-2026-018-hrdocs.pdf", 5242880, "manual_documentation", 4, D0-timedelta(days=40)+timedelta(hours=3), 2),
    ev(19, 3, 10, 7, "Cloud mailbox export recovered from a backup stored on the WD Elements external drive.",
       "/evidence/case-003/EVD-2026-019-mailbox.pst", 1073741824, "cloud_extraction", 9, D0-timedelta(days=40)+timedelta(hours=2,minutes=30), 2),
    ev(20, 3, None, 4, "Photographs of the administrator's workstation and desk area at the time of seizure.",
       "/evidence/case-003/EVD-2026-020-photos.zip", 41943040, "manual_documentation", 4, D0-timedelta(days=40)+timedelta(minutes=45), 2),

    # --- Case 4: CASE-2026-004 (5 items) ---
    ev(21, 4, 11, 8, "Full mobile backup extracted from the suspect's iPhone 13 used to send the phishing email.",
       "/evidence/case-004/EVD-2026-021-backup.tar", 8589934592, "logical_extraction", 3, D0+timedelta(days=10,hours=1), 2),
    ev(22, 4, 12, 7, "Mailbox export from the ProBook 440 laptop containing phishing campaign correspondence.",
       "/evidence/case-004/EVD-2026-022-mailbox.pst", 268435456, "logical_extraction", 3, D0+timedelta(days=10,hours=1,minutes=30), 2),
    ev(23, 4, 13, 3, "Browser and application logs extracted from the Galaxy Tab A8.",
       "/evidence/case-004/EVD-2026-023-browserlogs.zip", 6291456, "logical_extraction", 10, D0+timedelta(days=10,hours=2), 2),
    ev(24, 4, None, 5, "Printed copies of the phishing email as received by the municipal finance clerk.",
       "/evidence/case-004/EVD-2026-024-phishingemail.pdf", 1048576, "manual_documentation", 10, D0+timedelta(days=10,hours=2,minutes=30), 2),
    ev(25, 4, None, 6, "Network capture of the municipal finance office covering the credential-disclosure incident.",
       "/evidence/case-004/EVD-2026-025.pcap", 157286400, "network_capture", 3, D0+timedelta(days=10,hours=3), 2),

    # --- Case 5: CASE-2026-005 (5 items) ---
    ev(26, 5, 14, 8, "Mobile backup extracted from the victim's iPhone 12 used to access the cryptocurrency wallet app.",
       "/evidence/case-005/EVD-2026-026-backup.tar", 4294967296, "logical_extraction", 1, D0-timedelta(days=70)+timedelta(hours=1), 5),
    ev(27, 5, 15, 1, "Disk image of the ZenBook 14 laptop where the seed-phrase note was stored.",
       "/evidence/case-005/EVD-2026-027.E01", 549755813888, "physical_extraction", 1, D0-timedelta(days=70)+timedelta(hours=1,minutes=30), 5),
    ev(28, 5, 15, 2, "RAM capture of the ZenBook 14 laptop at the time of seizure.",
       "/evidence/case-005/EVD-2026-028.mem", 17179869184, "logical_extraction", 7, D0-timedelta(days=70)+timedelta(hours=1,minutes=45), 5),
    ev(29, 5, None, 5, "Scanned printout of the blockchain transaction history for the drained wallet.",
       "/evidence/case-005/EVD-2026-029-txnhistory.pdf", 3145728, "manual_documentation", 1, D0-timedelta(days=70)+timedelta(hours=2), 5),
    ev(30, 5, None, 4, "Photographs documenting the laptop and surrounding desk area at the time of seizure.",
       "/evidence/case-005/EVD-2026-030-photos.zip", 20971520, "manual_documentation", 7, D0-timedelta(days=70)+timedelta(hours=2,minutes=15), 5),
]
insert("evidence", ["evidence_number","case_id","device_id","evidence_type_id","description","file_path",
                     "file_size_bytes","acquisition_method","collected_by","collected_at",
                     "storage_location_id","integrity_status"], evidence)
# evidence_id 1..30 in the order above (EVD-2026-001..030)

print("Part 5 (evidence) generated:", len(OUT), "statements so far, total evidence rows:", len(evidence))
with open("/home/claude/seedgen/part5.sql", "w") as f:
    f.write("\n".join(OUT))

# =====================================================================
# Build lookup maps from data already generated (single source of truth)
# =====================================================================
case_jurisdiction = {i+1: c[5] for i, c in enumerate(cases)}      # case_id -> jurisdiction_location_id
device_seized_loc = {i+1: d[9] for i, d in enumerate(devices)}    # device_id -> seized_location_id
case_investigator_map = {1: [1,2,4], 2: [5,6], 3: [9,4], 4: [10,3], 5: [1,7]}

# =====================================================================
# 15. evidence_hashes — generated via MySQL's own SHA2() function
#     (one original hash per evidence item, plus a small number of
#     later re-verification hashes on the flagship case's items)
# =====================================================================
emit("-- =====================================================================")
emit("-- 15. evidence_hashes")
emit("-- Uses MySQL's native SHA2() to derive a realistic, valid 64-char hex")
emit("-- hash per evidence item directly from its evidence_number + acquisition")
emit("-- timestamp, so every row is guaranteed unique and passes the")
emit("-- chk_evidence_hashes_length CHECK constraint (>= 32 chars) trivially.")
emit("-- =====================================================================")
emit("""INSERT INTO evidence_hashes (evidence_id, hash_algorithm, hash_value, computed_by, computed_at, is_original)
SELECT
    e.evidence_id,
    'SHA256',
    SHA2(CONCAT(e.evidence_number, '|original|', e.collected_at), 256),
    e.collected_by,
    e.collected_at + INTERVAL 15 MINUTE,
    1
FROM evidence e;
""")
emit("-- Re-verification hashes for the flagship case's evidence (demonstrates")
emit("-- is_original = 0 and repeated integrity checks over time).")
emit("""INSERT INTO evidence_hashes (evidence_id, hash_algorithm, hash_value, computed_by, computed_at, is_original)
SELECT
    e.evidence_id,
    'SHA256',
    SHA2(CONCAT(e.evidence_number, '|reverify-30d|', e.collected_at), 256),
    e.collected_by,
    e.collected_at + INTERVAL 30 DAY,
    0
FROM evidence e
WHERE e.case_id = 1;
""")

# =====================================================================
# 16. chain_of_custody — computed from the evidence + investigator maps
#     built above. Flagship case gets a 4-step chain per item; every
#     other case gets a 2-step chain. Total rows: 8*4 + 22*2 = 76.
# =====================================================================
emit("-- =====================================================================")
emit("-- 16. chain_of_custody")
emit("-- =====================================================================")
custody_rows = []
LOC_NAME = {1:"Central Evidence Locker",2:"Regional Forensics Lab",3:"State Cyber Cell HQ",
            4:"Metro Evidence Storage Facility",5:"Southern Digital Forensics Lab",
            6:"District Court Complex",7:"Eastern Zone Evidence Locker",8:"National Cyber Forensics Lab"}

for idx, e in enumerate(evidence):
    eid = idx + 1
    case_id, device_id, collector, collected_at, storeloc = e[1], e[2], e[8], e[9], e[10]
    inv_list = case_investigator_map[case_id]
    others = [u for u in inv_list if u != collector]
    seize_loc = device_seized_loc.get(device_id) if device_id else case_jurisdiction[case_id]

    # Step 1: collected
    custody_rows.append((eid, None, collector, "collected", seize_loc, collected_at,
                          "Evidence collected at seizure site and logged into initial custody."))
    receiver = others[0]
    step2_ts = collected_at + timedelta(hours=2)
    custody_rows.append((eid, collector, receiver, "received", storeloc, step2_ts,
                          f"Received at {LOC_NAME[storeloc]} and logged in for forensic processing."))

    if case_id == 1:
        analyzer = others[1] if len(others) > 1 else receiver
        step3_ts = collected_at + timedelta(days=1)
        step4_ts = collected_at + timedelta(days=1, hours=3)
        custody_rows.append((eid, receiver, analyzer, "analyzed", storeloc, step3_ts,
                              "Checked out of controlled storage for active forensic analysis."))
        custody_rows.append((eid, analyzer, receiver, "stored", storeloc, step4_ts,
                              "Analysis session complete; evidence re-secured in controlled storage."))

insert("chain_of_custody", ["evidence_id","transferred_from","transferred_to","custody_action",
                             "location_id","custody_timestamp","remarks"], custody_rows)
print("chain_of_custody rows generated:", len(custody_rows))

print("Part 6 (hashes, custody) generated:", len(OUT), "statements so far")
with open("/home/claude/seedgen/part6.sql", "w") as f:
    f.write("\n".join(OUT))

# =====================================================================
# 17. evidence_examinations (20) — 4/5/4/4/3 across the 5 cases
# =====================================================================
emit("-- =====================================================================")
emit("-- 17. evidence_examinations")
emit("-- =====================================================================")
TOOL = {"disk":1, "encase":2, "ftk":3, "wireshark":4, "volatility":5, "cellebrite":6, "xways":7, "axiom":8}
# (evidence_id, tool_id, examiner_id, examination_type, started_at, completed_at, findings_summary, status)
examinations = [
    # Case 1 (evidence 1-8) — 4 examinations
    (1, 6, 2, "data_recovery", D0+timedelta(days=1), D0+timedelta(days=1,hours=6),
     "Recovered deleted messaging app data referencing an external vendor account under investigation.", "completed"),
    (2, 1, 2, "static_analysis", D0+timedelta(days=1,hours=2), D0+timedelta(days=1,hours=9),
     "File-system timeline shows batch creation of invoice PDFs outside normal business hours.", "completed"),
    (3, 5, 4, "dynamic_analysis", D0+timedelta(days=1,hours=1), None,
     "Memory analysis in progress; reviewing process list for unauthorized remote-access tooling.", "in_progress"),
    (7, 8, 2, "timeline_analysis", D0+timedelta(days=2), D0+timedelta(days=2,hours=5),
     "Email correspondence timeline corroborates invoice submission dates from three flagged vendor accounts.", "peer_reviewed"),
    # Case 2 (evidence 9-14) — 5 examinations
    (9, 2, 6, "static_analysis", D0+timedelta(days=7), D0+timedelta(days=7,hours=8),
     "Identified ransomware binary and lateral-movement artifacts consistent with a known ransomware family.", "completed"),
    (10, 5, 6, "dynamic_analysis", D0+timedelta(days=7,hours=1), D0+timedelta(days=7,hours=10),
     "Volatile memory confirms an active encryption process and an outbound C2 connection at time of capture.", "completed"),
    (11, 4, 5, "network_analysis", D0+timedelta(days=7,hours=2), D0+timedelta(days=7,hours=7),
     "Router logs show an unusual outbound connection shortly before the encryption event began.", "completed"),
    (12, 4, 5, "network_analysis", D0+timedelta(days=7,hours=3), None,
     "Deep packet inspection of the capture ongoing to map the full extent of data exfiltration.", "in_progress"),
    (13, 6, 6, "file_carving", D0+timedelta(days=8), D0+timedelta(days=8,hours=6),
     "Carved partially-encrypted files to recover fragments of the pre-encryption directory structure.", "completed"),
    # Case 3 (evidence 15-20) — 4 examinations
    (15, 3, 9, "static_analysis", D0-timedelta(days=39), D0-timedelta(days=39)+timedelta(hours=7),
     "File access timestamps show bulk database export activity in the two weeks before resignation.", "completed"),
    (17, 3, 9, "data_recovery", D0-timedelta(days=39)+timedelta(hours=8), D0-timedelta(days=38),
     "Recovered previously deleted export archive from unallocated space on the USB drive.", "peer_reviewed"),
    (19, 7, 9, "static_analysis", D0-timedelta(days=38), D0-timedelta(days=37),
     "Mailbox review identifies correspondence with a personal email address matching the export window.", "completed"),
    (16, 1, 4, "timeline_analysis", D0-timedelta(days=37), D0-timedelta(days=36),
     "Cross-referenced database logs against badge-access records to confirm after-hours presence.", "completed"),
    # Case 4 (evidence 21-25) — 4 examinations
    (21, 6, 3, "mobile_extraction" if False else "data_recovery", D0+timedelta(days=11), D0+timedelta(days=11,hours=5),
     "Extracted sent-message history confirming the phishing email was composed and sent from this device.", "completed"),
    (22, 8, 3, "static_analysis", D0+timedelta(days=11,hours=1), D0+timedelta(days=11,hours=6),
     "Mailbox headers confirm domain spoofing consistent with the vendor-impersonation phishing template.", "completed"),
    (23, 7, 10, "static_analysis", D0+timedelta(days=11,hours=2), None,
     "Reviewing cached browser sessions for evidence of the fraudulent payment portal.", "in_progress"),
    (25, 4, 3, "network_analysis", D0+timedelta(days=12), D0+timedelta(days=12,hours=4),
     "Traffic capture confirms the finance office workstation submitted credentials to the spoofed portal.", "completed"),
    # Case 5 (evidence 26-30) — 3 examinations
    (26, 6, 1, "data_recovery", D0-timedelta(days=69), D0-timedelta(days=69)+timedelta(hours=5),
     "Recovered wallet application session data confirming the device used to authorize the transfer.", "completed"),
    (27, 1, 7, "static_analysis", D0-timedelta(days=69)+timedelta(hours=1), D0-timedelta(days=69)+timedelta(hours=9),
     "Located an unencrypted notes file containing what appears to be the wallet seed phrase.", "completed"),
    (28, 5, 7, "dynamic_analysis", D0-timedelta(days=69)+timedelta(hours=2), D0-timedelta(days=69)+timedelta(hours=6),
     "Memory artifacts consistent with clipboard-hijacking malware active at the time of the transfer.", "peer_reviewed"),
]
insert("evidence_examinations", ["evidence_id","tool_id","examiner_id","examination_type",
                                  "started_at","completed_at","findings_summary","examination_status"],
       examinations)
print("evidence_examinations rows generated:", len(examinations))

print("Part 7 (examinations) generated:", len(OUT), "statements so far")
with open("/home/claude/seedgen/part7.sql", "w") as f:
    f.write("\n".join(OUT))

# =====================================================================
# 18. forensic_reports (10) — case1 gets 3, others 2/2/2/1
# =====================================================================
emit("-- =====================================================================")
emit("-- 18. forensic_reports")
emit("-- =====================================================================")
# (report_number, case_id, title, prepared_by, reviewed_by, report_status, created_at, finalized_at)
reports = [
    ("RPT-2026-001", 1, "Preliminary Forensic Findings - Corporate Cyber Fraud", 2, 4, "finalized",
     D0+timedelta(days=2), D0+timedelta(days=3)),
    ("RPT-2026-002", 1, "Device Examination Report - Seized Laptop and Desktop", 2, 1, "approved",
     D0+timedelta(days=3), None),
    ("RPT-2026-003", 1, "Vendor Correspondence and Email Timeline Analysis", 2, None, "draft",
     D0+timedelta(days=4), None),
    ("RPT-2026-004", 2, "Ransomware Incident Technical Report", 6, 5, "under_review",
     D0+timedelta(days=8), None),
    ("RPT-2026-005", 2, "Network Traffic and Exfiltration Assessment", 5, None, "submitted",
     D0+timedelta(days=9), None),
    ("RPT-2026-006", 3, "Data Exfiltration Findings Report", 9, 4, "finalized",
     D0-timedelta(days=37), D0-timedelta(days=35)),
    ("RPT-2026-007", 3, "USB Media Recovery and Timeline Report", 9, 4, "approved",
     D0-timedelta(days=36), None),
    ("RPT-2026-008", 4, "Phishing Campaign Technical Findings", 3, 10, "under_review",
     D0+timedelta(days=12), None),
    ("RPT-2026-009", 4, "Mobile Device Extraction Summary", 3, None, "submitted",
     D0+timedelta(days=13), None),
    ("RPT-2026-010", 5, "Cryptocurrency Wallet Theft Final Report", 1, 7, "finalized",
     D0-timedelta(days=25), D0-timedelta(days=20)),
]
insert("forensic_reports", ["report_number","case_id","title","prepared_by","reviewed_by",
                             "report_status","created_at","finalized_at"], reports)
# report_id 1..10 in order above

# =====================================================================
# 19. report_versions (14) — first two case-1 reports get 2 versions,
#     RPT-2026-005 and RPT-2026-009 also get 2 versions, rest get 1
# =====================================================================
emit("-- =====================================================================")
emit("-- 19. report_versions")
emit("-- =====================================================================")
# (report_id, version_number, file_path, content_hash_source, change_summary, created_by, created_at)
def rv(report_id, vnum, path, summary, created_by, ts):
    return (report_id, vnum, path, None, summary, created_by, ts)

report_versions = [
    rv(1, 1, "/reports/RPT-2026-001-v1.pdf", "Initial draft circulated for supervisor review.", 2, D0+timedelta(days=2)),
    rv(1, 2, "/reports/RPT-2026-001-v2.pdf", "Revised per supervisor feedback; added vendor cross-reference appendix.", 2, D0+timedelta(days=3)),
    rv(2, 1, "/reports/RPT-2026-002-v1.pdf", "Initial device examination summary.", 2, D0+timedelta(days=3)),
    rv(2, 2, "/reports/RPT-2026-002-v2.pdf", "Added memory-dump findings after Lead Investigator review.", 2, D0+timedelta(days=3,hours=6)),
    rv(3, 1, "/reports/RPT-2026-003-v1.pdf", "First draft of the email timeline analysis.", 2, D0+timedelta(days=4)),
    rv(4, 1, "/reports/RPT-2026-004-v1.pdf", "Initial technical report on the ransomware incident.", 6, D0+timedelta(days=8)),
    rv(5, 1, "/reports/RPT-2026-005-v1.pdf", "Initial network/exfiltration assessment.", 5, D0+timedelta(days=9)),
    rv(5, 2, "/reports/RPT-2026-005-v2.pdf", "Updated with deep-packet-inspection findings.", 5, D0+timedelta(days=9,hours=10)),
    rv(6, 1, "/reports/RPT-2026-006-v1.pdf", "Final data exfiltration findings report.", 9, D0-timedelta(days=37)),
    rv(7, 1, "/reports/RPT-2026-007-v1.pdf", "USB media recovery and timeline summary.", 9, D0-timedelta(days=36)),
    rv(8, 1, "/reports/RPT-2026-008-v1.pdf", "Initial phishing campaign technical findings.", 3, D0+timedelta(days=12)),
    rv(9, 1, "/reports/RPT-2026-009-v1.pdf", "Initial mobile extraction summary.", 3, D0+timedelta(days=13)),
    rv(9, 2, "/reports/RPT-2026-009-v2.pdf", "Added browser cache analysis section.", 3, D0+timedelta(days=13,hours=8)),
    rv(10, 1, "/reports/RPT-2026-010-v1.pdf", "Final cryptocurrency wallet theft report.", 1, D0-timedelta(days=25)),
]
# content_hash left NULL in tuples above (index 3); build final rows with SQL NULL for that column
final_rv_rows = [(r[0], r[1], r[2], None, r[4], r[5], r[6]) for r in report_versions]
insert("report_versions", ["report_id","version_number","file_path","content_hash","change_summary",
                            "created_by","created_at"], final_rv_rows)
print("forensic_reports:", len(reports), " report_versions:", len(final_rv_rows))

print("Part 8 (reports) generated:", len(OUT), "statements so far")
with open("/home/claude/seedgen/part8.sql", "w") as f:
    f.write("\n".join(OUT))

# =====================================================================
# 20. case_timeline (target: 54 — 14 for the flagship case, 10 each
#     for the other four cases)
# =====================================================================
emit("-- =====================================================================")
emit("-- 20. case_timeline")
emit("-- =====================================================================")
# (case_id, event_type, event_description, related_table, related_record_id, event_timestamp, recorded_by)
timeline = []

def tl(case_id, etype, desc, rtable, rid, ts, by):
    timeline.append((case_id, etype, desc, rtable, rid, ts, by))

# --- Case 1 flagship: 14 events ---
tl(1, "case_opened", "Case CASE-2026-001 opened following an internal fraud referral from the finance department.", "cases", 1, D0, 1)
tl(1, "evidence_collected", "Seizure team collected 4 devices from the finance department office.", "devices", 1, D0+timedelta(hours=1), 1)
tl(1, "evidence_collected", "Disk images and memory capture acquired from suspect's laptop and phone.", "evidence", 2, D0+timedelta(hours=2,minutes=30), 2)
tl(1, "evidence_collected", "Vendor invoice documents and mailbox archive collected for review.", "evidence", 6, D0+timedelta(hours=4), 4)
tl(1, "custody_transfer", "All seized devices received into the Regional Forensics Lab evidence queue.", "chain_of_custody", None, D0+timedelta(hours=6), 2)
tl(1, "examination_started", "Static analysis of the finance manager's laptop disk image began.", "evidence_examinations", 2, D0+timedelta(days=1,hours=2), 2)
tl(1, "examination_started", "Mobile device forensic recovery began on the seized Galaxy S23.", "evidence_examinations", 1, D0+timedelta(days=1), 2)
tl(1, "examination_completed", "Recovered deleted messaging data referencing the flagged vendor account.", "evidence_examinations", 1, D0+timedelta(days=1,hours=6), 2)
tl(1, "examination_completed", "Email timeline analysis corroborated fraudulent invoice submission dates.", "evidence_examinations", 7, D0+timedelta(days=2,hours=5), 2)
tl(1, "report_filed", "Preliminary Forensic Findings report (RPT-2026-001) submitted for review.", "forensic_reports", 1, D0+timedelta(days=2), 2)
tl(1, "report_filed", "Device Examination Report (RPT-2026-002) submitted for review.", "forensic_reports", 2, D0+timedelta(days=3), 2)
tl(1, "status_change", "Case status updated to UNDER_INVESTIGATION following confirmation of fraudulent transfers.", "cases", 1, D0+timedelta(days=3,hours=2), 4)
tl(1, "report_filed", "Vendor Correspondence and Email Timeline Analysis (RPT-2026-003) drafted.", "forensic_reports", 3, D0+timedelta(days=4), 2)
tl(1, "other", "Case Supervisor requested an extended review of the vendor cross-reference appendix.", "forensic_reports", 1, D0+timedelta(days=4,hours=3), 4)

# --- Case 2: 10 events ---
tl(2, "case_opened", "Case CASE-2026-002 opened after an overnight ransomware encryption event was detected.", "cases", 2, D0+timedelta(days=6), 5)
tl(2, "evidence_collected", "Order-management server and affected laptop imaged on-site.", "devices", 5, D0+timedelta(days=6,hours=2), 6)
tl(2, "evidence_collected", "Full packet capture of the logistics network acquired.", "evidence", 12, D0+timedelta(days=6,hours=4), 5)
tl(2, "custody_transfer", "Server disk image transported to the National Cyber Forensics Lab for priority analysis.", "chain_of_custody", None, D0+timedelta(days=6,hours=6), 6)
tl(2, "examination_started", "Static analysis of the server disk image identified the ransomware binary.", "evidence_examinations", 5, D0+timedelta(days=7), 6)
tl(2, "examination_completed", "Memory analysis confirmed an active C2 connection at time of capture.", "evidence_examinations", 6, D0+timedelta(days=7,hours=10), 6)
tl(2, "examination_started", "Deep packet inspection of the network capture began to trace data exfiltration.", "evidence_examinations", 8, D0+timedelta(days=7,hours=3), 5)
tl(2, "report_filed", "Ransomware Incident Technical Report (RPT-2026-004) submitted for review.", "forensic_reports", 4, D0+timedelta(days=8), 6)
tl(2, "report_filed", "Network Traffic and Exfiltration Assessment (RPT-2026-005) submitted.", "forensic_reports", 5, D0+timedelta(days=9), 5)
tl(2, "status_change", "Priority escalated to CRITICAL following confirmation of a double-extortion threat.", "cases", 2, D0+timedelta(days=6,hours=8), 5)

# --- Case 3: 10 events ---
tl(3, "case_opened", "Case CASE-2026-003 opened following an internal alert on unusual database export volume.", "cases", 3, D0-timedelta(days=40), 4)
tl(3, "evidence_collected", "Workstation, USB drive, and external HDD seized from the administrator's desk.", "devices", 8, D0-timedelta(days=40)+timedelta(hours=1), 4)
tl(3, "custody_transfer", "Seized media received at the Regional Forensics Lab for imaging.", "chain_of_custody", None, D0-timedelta(days=40)+timedelta(hours=3), 9)
tl(3, "examination_started", "Static analysis of the workstation disk image began.", "evidence_examinations", 9, D0-timedelta(days=39), 9)
tl(3, "examination_completed", "File access timestamps confirmed bulk database export activity pre-resignation.", "evidence_examinations", 9, D0-timedelta(days=39)+timedelta(hours=7), 9)
tl(3, "examination_completed", "Deleted export archive recovered from unallocated space on the USB drive.", "evidence_examinations", 11, D0-timedelta(days=38), 9)
tl(3, "report_filed", "Data Exfiltration Findings Report (RPT-2026-006) finalized.", "forensic_reports", 6, D0-timedelta(days=37), 9)
tl(3, "report_filed", "USB Media Recovery and Timeline Report (RPT-2026-007) approved.", "forensic_reports", 7, D0-timedelta(days=36), 9)
tl(3, "status_change", "Case status updated to CLOSED following approval of the final findings report.", "cases", 3, D0-timedelta(days=3), 4)
tl(3, "case_closed", "Case CASE-2026-003 formally closed; devices released back to the organization.", "cases", 3, D0-timedelta(days=3), 4)

# --- Case 4: 10 events ---
tl(4, "case_opened", "Case CASE-2026-004 opened after a reported fraudulent payment redirection attempt.", "cases", 4, D0+timedelta(days=10), 10)
tl(4, "evidence_collected", "Suspect's phone, laptop, and tablet seized following identification of the sender.", "devices", 11, D0+timedelta(days=10,hours=1), 10)
tl(4, "evidence_collected", "Printed phishing email and network capture from the finance office collected.", "evidence", 25, D0+timedelta(days=10,hours=3), 3)
tl(4, "custody_transfer", "Mobile device received at the Regional Forensics Lab for extraction.", "chain_of_custody", None, D0+timedelta(days=10,hours=3), 3)
tl(4, "examination_started", "Mobile extraction of the suspect's iPhone 13 began.", "evidence_examinations", 12, D0+timedelta(days=11), 3)
tl(4, "examination_completed", "Sent-message history confirmed the phishing email was composed on this device.", "evidence_examinations", 12, D0+timedelta(days=11,hours=5), 3)
tl(4, "examination_completed", "Traffic capture confirmed credential submission to the spoofed payment portal.", "evidence_examinations", 20, D0+timedelta(days=12,hours=4), 3)
tl(4, "report_filed", "Phishing Campaign Technical Findings (RPT-2026-008) submitted for review.", "forensic_reports", 8, D0+timedelta(days=12), 3)
tl(4, "report_filed", "Mobile Device Extraction Summary (RPT-2026-009) submitted.", "forensic_reports", 9, D0+timedelta(days=13), 3)
tl(4, "other", "Legal & Compliance Unit requested a supplementary browser-cache analysis.", "evidence_examinations", 15, D0+timedelta(days=13,hours=2), 10)

# --- Case 5: 10 events ---
tl(5, "case_opened", "Case CASE-2026-005 opened after the victim reported an unauthorized wallet drain.", "cases", 5, D0-timedelta(days=70), 1)
tl(5, "evidence_collected", "Victim's phone and laptop voluntarily surrendered for imaging.", "devices", 14, D0-timedelta(days=70)+timedelta(hours=1), 1)
tl(5, "custody_transfer", "Laptop disk image received at the Southern Digital Forensics Lab.", "chain_of_custody", None, D0-timedelta(days=70)+timedelta(hours=3), 7)
tl(5, "examination_started", "Recovery of wallet application session data began on the mobile backup.", "evidence_examinations", 17, D0-timedelta(days=69), 1)
tl(5, "examination_completed", "Unencrypted notes file containing the wallet seed phrase was located.", "evidence_examinations", 18, D0-timedelta(days=69)+timedelta(hours=9), 7)
tl(5, "examination_completed", "Memory artifacts consistent with clipboard-hijacking malware identified.", "evidence_examinations", 19, D0-timedelta(days=69)+timedelta(hours=6), 7)
tl(5, "report_filed", "Cryptocurrency Wallet Theft Final Report (RPT-2026-010) finalized.", "forensic_reports", 10, D0-timedelta(days=25), 1)
tl(5, "status_change", "Case status updated to ARCHIVED after final report issuance and device return.", "cases", 5, D0-timedelta(days=20), 1)
tl(5, "case_closed", "Case CASE-2026-005 archived; no further recovery action pursued by the victim.", "cases", 5, D0-timedelta(days=20), 1)
tl(5, "other", "Blockchain analytics vendor report attached confirming the destination wallet cluster.", "evidence", 29, D0-timedelta(days=24), 1)

insert("case_timeline", ["case_id","event_type","event_description","related_table","related_record_id",
                          "event_timestamp","recorded_by"], timeline)
print("case_timeline rows generated:", len(timeline))

print("Part 9 (timeline) generated:", len(OUT), "statements so far")
with open("/home/claude/seedgen/part9.sql", "w") as f:
    f.write("\n".join(OUT))

# =====================================================================
# 21. audit_logs (100) — deterministic, cycling through realistic
#     INSERT/UPDATE/DELETE-style actions across users and tables
# =====================================================================
emit("-- =====================================================================")
emit("-- 21. audit_logs")
emit("-- =====================================================================")
import json as _json

# A pool of (table_name, record_id_max, action_type, old_json, new_json) templates,
# cycled deterministically against users and a timestamp ladder to reach 100 rows
# without any single row being an implausible duplicate.
audit_templates = [
    ("cases", 5, "UPDATE", {"status": "open"}, {"status": "under_investigation"}),
    ("cases", 5, "UPDATE", {"priority": "medium"}, {"priority": "high"}),
    ("evidence", 30, "INSERT", None, {"integrity_status": "intact"}),
    ("evidence", 30, "UPDATE", {"integrity_status": "intact"}, {"integrity_status": "under_verification"}),
    ("devices", 15, "UPDATE", {"device_status": "seized"}, {"device_status": "in_lab"}),
    ("devices", 15, "UPDATE", {"device_status": "in_lab"}, {"device_status": "under_examination"}),
    ("chain_of_custody", 76, "INSERT", None, {"custody_action": "received"}),
    ("evidence_examinations", 20, "UPDATE", {"examination_status": "scheduled"}, {"examination_status": "in_progress"}),
    ("evidence_examinations", 20, "UPDATE", {"examination_status": "in_progress"}, {"examination_status": "completed"}),
    ("forensic_reports", 10, "UPDATE", {"report_status": "draft"}, {"report_status": "submitted"}),
    ("forensic_reports", 10, "UPDATE", {"report_status": "submitted"}, {"report_status": "under_review"}),
    ("report_versions", 14, "INSERT", None, {"version_number": 1}),
    ("case_investigators", 11, "INSERT", None, {"role_in_case": "forensic_analyst"}),
    ("case_persons", 13, "INSERT", None, {"person_role": "witness"}),
    ("users", 10, "UPDATE", {"last_login_at": None}, {"last_login_at": "login_recorded"}),
    ("evidence_hashes", 38, "INSERT", None, {"hash_algorithm": "SHA256"}),
    ("case_timeline", 54, "INSERT", None, {"event_type": "status_change"}),
    ("cases", 5, "UPDATE", {"status": "under_investigation"}, {"status": "pending_review"}),
    ("evidence", 30, "UPDATE", {"storage_location_id": 2}, {"storage_location_id": 8}),
    ("devices", 15, "UPDATE", {"current_location_id": 3}, {"current_location_id": 2}),
]

IP_POOL = ["10.12.4.21","10.12.4.22","10.12.4.23","10.12.5.10","10.12.5.11",
           "192.168.20.14","192.168.20.15","192.168.20.16","172.16.8.5","172.16.8.6"]

audit_rows = []
n = 100
for i in range(n):
    template = audit_templates[i % len(audit_templates)]
    table_name, id_max, action, old_v, new_v = template
    user_id = (i % 10) + 1
    record_id = (i % id_max) + 1
    ts = D0 - timedelta(days=75) + timedelta(hours=i * 9)  # spread across the whole dataset's date range
    ip = IP_POOL[i % len(IP_POOL)]
    old_json = None if old_v is None else _json.dumps(old_v)
    new_json = None if new_v is None else _json.dumps(new_v)
    audit_rows.append((user_id, table_name, record_id, action, old_json, new_json, ts, ip))

# Special-case: a handful of system-generated rows with NULL user_id
for j in range(5):
    idx = 90 + j
    table_name, id_max, action, old_v, new_v = audit_templates[idx % len(audit_templates)]
    record_id = (idx % id_max) + 1
    ts = D0 - timedelta(days=75) + timedelta(hours=idx * 9)
    audit_rows[idx] = (None, table_name, record_id, "UPDATE",
                        _json.dumps({"note": "system_maintenance"}), _json.dumps({"note": "system_maintenance_complete"}),
                        ts, None)

insert("audit_logs", ["user_id","table_name","record_id","action_type","old_values","new_values",
                       "action_timestamp","ip_address"], audit_rows)
print("audit_logs rows generated:", len(audit_rows))

emit("COMMIT;")
emit("")
emit("SELECT 'FORGE-X seed data loaded successfully.' AS status;")

with open("/home/claude/forge-x/database/09_seed_data.sql", "w") as f:
    f.write("\n".join(OUT) + "\n")

print("\nTOTAL statements/lines written:", len(OUT))
print("Final file: /home/claude/forge-x/database/09_seed_data.sql")
