"""Build an install script for a SEPARATE test database (FORGE-X 2.0 Phase 6).

The opt-in workflow tests add users, cases and evidence that can never be
deleted (by design), so they must not run against your real forge_x_db.
This writes database/build/install_<name>.sql: the same schema, triggers,
views, procedures, reference data, grants and verification as a fresh
install, with the database name replaced. Your real database is never named.

    python tools\\build_test_database.py              (default name: forge_x_test)
    mysql -u root -p --default-character-set=utf8mb4 --table -e "source database/build/install_forge_x_test.sql"
    set MYSQL_DATABASE=forge_x_test
    flask --app run create-admin pytest_admin
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DB = ROOT / "database"
ORDER = ["schema.sql", "triggers.sql", "views.sql", "procedures.sql", "seed_reference.sql"]
REAL = "forge_x_db"


def build(name="forge_x_test"):
    if name == REAL or not re.fullmatch(r"[a-z][a-z0-9_]{2,40}", name):
        raise SystemExit(f"Refusing: choose a lowercase test database name other than {REAL}.")
    parts = [f"-- Generated by tools/build_test_database.py: a separate TEST database '{name}'.\n"
             f"-- It drops and recreates {name} only. Your real database is never touched.\n"]
    for filename in ORDER:
        text = (DB / filename).read_text(encoding="utf-8")
        parts.append(f"\n-- ===== {filename} =====\n" + re.sub(rf"\b{REAL}\b", name, text))
    # The application role gets the same least-privilege rights on the test database.
    grants = [line for line in (DB / "app_user.sql").read_text(encoding="utf-8").splitlines()
              if line.startswith("GRANT ") and f"{REAL}." in line and "forge_x_app_role" in line]
    parts.append("\n-- ===== grants for the application role on the test database =====\n"
                 "CREATE ROLE IF NOT EXISTS 'forge_x_app_role';\n"
                 + "\n".join(re.sub(rf"\b{REAL}\b", name, g) for g in grants) + "\n")
    parts.append("\n-- ===== verify.sql =====\n" + re.sub(rf"\b{REAL}\b", name, (DB / "verify.sql").read_text(encoding="utf-8")))
    sql = "".join(parts)
    leftover = re.findall(rf"\b{REAL}\b", sql)
    if leftover:
        raise SystemExit(f"Refusing: {len(leftover)} references to {REAL} remain.")
    out = DB / "build" / f"install_{name}.sql"
    out.parent.mkdir(exist_ok=True)
    out.write_text(sql, encoding="utf-8")
    return out, len(grants)


if __name__ == "__main__":
    path, grants = build(*(sys.argv[1:2] or []))
    name = path.stem.replace("install_", "")
    print(f"Wrote {path.relative_to(ROOT)} ({grants} grants for forge_x_app_role).")
    print("Next (as root, then with the test database selected for this window only):")
    print(f'  mysql -u root -p --default-character-set=utf8mb4 --table -e "source database/build/{path.name}"')
    print(f"  set MYSQL_DATABASE={name}")
    print("  flask --app run create-admin pytest_admin")
    print("  python tools\\stability_report.py --with-write-tests")
